//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoThemeChanger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoThemeChanger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string applyButton {
            get {
                return ResourceManager.GetString("applyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic theme switching.
        /// </summary>
        public static string autoCheckBox {
            get {
                return ResourceManager.GetString("autoCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 hour clock.
        /// </summary>
        public static string cb12HourTime {
            get {
                return ResourceManager.GetString("cb12HourTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only visible in dark mode.
        ///If you run into issues: please increase the switching delay in settings. .
        /// </summary>
        public static string cbAccentColor {
            get {
                return ResourceManager.GetString("cbAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for updates in background.
        /// </summary>
        public static string cbBackgroundUpdate {
            get {
                return ResourceManager.GetString("cbBackgroundUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch after Connected Standby.
        /// </summary>
        public static string cbConnectedStandby {
            get {
                return ResourceManager.GetString("cbConnectedStandby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile devices, like Microsoft Surface products, are using a new kind of standby mode. 
        ///Enabling this option makes sure that Auto Dark Mode immediately switches the theme after waking up your computer. 
        ///But it also reduces the battery life! ONLY activate if necessary!.
        /// </summary>
        public static string cbConnectedStandbyTooltip {
            get {
                return ResourceManager.GetString("cbConnectedStandbyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is disabled, because you haven&apos;t installed the Windows 10 April 2019 Update on your machine..
        /// </summary>
        public static string cmb1903 {
            get {
                return ResourceManager.GetString("cmb1903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color for Taskbar.
        /// </summary>
        public static string cmbAccentColor {
            get {
                return ResourceManager.GetString("cmbAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust to theme.
        /// </summary>
        public static string cmbAdjTheme {
            get {
                return ResourceManager.GetString("cmbAdjTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always dark.
        /// </summary>
        public static string cmbAlwDark {
            get {
                return ResourceManager.GetString("cmbAlwDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always white.
        /// </summary>
        public static string cmbAlwWhite {
            get {
                return ResourceManager.GetString("cmbAlwWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently:.
        /// </summary>
        public static string dbCurrently {
            get {
                return ResourceManager.GetString("dbCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper for dark theme.
        /// </summary>
        public static string dbDark {
            get {
                return ResourceManager.GetString("dbDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete/Disable.
        /// </summary>
        public static string dbDel {
            get {
                return ResourceManager.GetString("dbDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe your picture file is corrupted or the path doesn&apos;t exist..
        /// </summary>
        public static string dbErrorText {
            get {
                return ResourceManager.GetString("dbErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick file.
        /// </summary>
        public static string dbFilePicker {
            get {
                return ResourceManager.GetString("dbFilePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper for light theme.
        /// </summary>
        public static string dbLight {
            get {
                return ResourceManager.GetString("dbLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Background.
        /// </summary>
        public static string dbMainHeader {
            get {
                return ResourceManager.GetString("dbMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string dbPictures {
            get {
                return ResourceManager.GetString("dbPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t generate a preview of your image, sorry!.
        /// </summary>
        public static string dbPreviewError {
            get {
                return ResourceManager.GetString("dbPreviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t save your settings, sorry!.
        /// </summary>
        public static string dbSavedError {
            get {
                return ResourceManager.GetString("dbSavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select two wallpaper.
        /// </summary>
        public static string dbSaveToolTip {
            get {
                return ResourceManager.GetString("dbSaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image.
        /// </summary>
        public static string dbSelectImage {
            get {
                return ResourceManager.GetString("dbSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Desktop Background.
        /// </summary>
        public static string dbTitle {
            get {
                return ResourceManager.GetString("dbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use current background.
        /// </summary>
        public static string dbUseCurrent {
            get {
                return ResourceManager.GetString("dbUseCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable features for Windows 1903.
        /// </summary>
        public static string debugModeCheckBox {
            get {
                return ResourceManager.GetString("debugModeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! Thanks for using Auto Dark Mode. I hope you like it so far :)
        ///
        ///Yes, this developer really created a popup to remind people that he accepts donations via paypal. What a shame!
        ///
        ///But hey, this app makes your everyday life a bit easier. Even a small donation makes me happy :D
        ///
        ///Do you want to open the PayPal donation page now?.
        /// </summary>
        public static string donationDescription {
            get {
                return ResourceManager.GetString("donationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like Auto Dark Mode?.
        /// </summary>
        public static string donationTitle {
            get {
                return ResourceManager.GetString("donationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Your input is invalid.
        /// </summary>
        public static string errorNumberInput {
            get {
                return ResourceManager.GetString("errorNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        public static string errorOcurredTitle {
            get {
                return ResourceManager.GetString("errorOcurredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but we couldn&apos;t apply your settings.
        ///
        ///Here are some things you can try:
        ///- Uninstall and then reinstall auto dark mode.
        ///- Try to run Auto Dark Mode as administrator.
        ///- If you enabled Desktop Wallpaper, disable the feature and try again.
        ///
        ///If these things didn&apos;t help, you can comment the GitHub issue with posting a screenshot of your error. You can access the issue by clicking the &quot;Yes&quot; button..
        /// </summary>
        public static string errorThemeApply {
            get {
                return ResourceManager.GetString("errorThemeApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps:.
        /// </summary>
        public static string lblApps {
            get {
                return ResourceManager.GetString("lblApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: Armin Osaj © 2019.
        /// </summary>
        public static string lblAuthor {
            get {
                return ResourceManager.GetString("lblAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom start time.
        /// </summary>
        public static string lblCustomStart {
            get {
                return ResourceManager.GetString("lblCustomStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string lblDark {
            get {
                return ResourceManager.GetString("lblDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        public static string lblDarkTheme {
            get {
                return ResourceManager.GetString("lblDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge (old version):.
        /// </summary>
        public static string lblEdge {
            get {
                return ResourceManager.GetString("lblEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string lblLight {
            get {
                return ResourceManager.GetString("lblLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        public static string lblLightTheme {
            get {
                return ResourceManager.GetString("lblLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string lblOffset {
            get {
                return ResourceManager.GetString("lblOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch current theme.
        /// </summary>
        public static string lblSwitchTheme {
            get {
                return ResourceManager.GetString("lblSwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System:.
        /// </summary>
        public static string lblSystem {
            get {
                return ResourceManager.GetString("lblSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used third party software.
        /// </summary>
        public static string lblThirdParty {
            get {
                return ResourceManager.GetString("lblThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator: Armin Osaj.
        /// </summary>
        public static string lblTranslator {
            get {
                return ResourceManager.GetString("lblTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string lblUpdates {
            get {
                return ResourceManager.GetString("lblUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Location Service.
        /// </summary>
        public static string locationCheckBox {
            get {
                return ResourceManager.GetString("locationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to a Windows bug the taskbar doesn&apos;t properly switch its colour in battery saver mode. Please turn off battery saver if you run into issues..
        /// </summary>
        public static string msgBatterySaver {
            get {
                return ResourceManager.GetString("msgBatterySaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changes were saved!.
        /// </summary>
        public static string msgChangesSaved {
            get {
                return ResourceManager.GetString("msgChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on apply to save changes.
        /// </summary>
        public static string msgClickApply {
            get {
                return ResourceManager.GetString("msgClickApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string msgClose {
            get {
                return ResourceManager.GetString("msgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download update.
        /// </summary>
        public static string msgDownloadUpd {
            get {
                return ResourceManager.GetString("msgDownloadUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error occurred :(.
        /// </summary>
        public static string msgErrorOcc {
            get {
                return ResourceManager.GetString("msgErrorOcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The App needs permission to location.
        /// </summary>
        public static string msgLocPerm {
            get {
                return ResourceManager.GetString("msgLocPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string msgNo {
            get {
                return ResourceManager.GetString("msgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no new updates are available..
        /// </summary>
        public static string msgNoUpd {
            get {
                return ResourceManager.GetString("msgNoUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching your location....
        /// </summary>
        public static string msgSearchLoc {
            get {
                return ResourceManager.GetString("msgSearchLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching for update....
        /// </summary>
        public static string msgSearchUpd {
            get {
                return ResourceManager.GetString("msgSearchUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: We couldn&apos;t read your current theme..
        /// </summary>
        public static string msgThemeError {
            get {
                return ResourceManager.GetString("msgThemeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a new update is available!.
        /// </summary>
        public static string msgUpdateAvail {
            get {
                return ResourceManager.GetString("msgUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using Auto Dark Mode!
        ///
        ///A new version is available on GitHub with fixes and enhancements.
        ///Do you want to download it?
        ///
        ///Currently installed version: {0}, new version: {1}.
        /// </summary>
        public static string msgUpdaterText {
            get {
                return ResourceManager.GetString("msgUpdaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MsgYes {
            get {
                return ResourceManager.GetString("MsgYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string NavbarAbout {
            get {
                return ResourceManager.GetString("NavbarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string NavbarApps {
            get {
                return ResourceManager.GetString("NavbarApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavbarSettings {
            get {
                return ResourceManager.GetString("NavbarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string NavbarTime {
            get {
                return ResourceManager.GetString("NavbarTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string NavbarTitle {
            get {
                return ResourceManager.GetString("NavbarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper/Theme.
        /// </summary>
        public static string NavbarWallpaper {
            get {
                return ResourceManager.GetString("NavbarWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string offsetButton {
            get {
                return ResourceManager.GetString("offsetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenPath {
            get {
                return ResourceManager.GetString("OpenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set custom hours.
        /// </summary>
        public static string rbCustomHours {
            get {
                return ResourceManager.GetString("rbCustomHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From sunset to sunrise.
        /// </summary>
        public static string rbLocation {
            get {
                return ResourceManager.GetString("rbLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App restart required to see the changes.
        /// </summary>
        public static string restartNeeded {
            get {
                return ResourceManager.GetString("restartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay for switching taskbar colors (ms):.
        /// </summary>
        public static string SettingsAccentColorTimeout {
            get {
                return ResourceManager.GetString("SettingsAccentColorTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome, Firefox and Edge:.
        /// </summary>
        public static string TextBoxAppsBrowsers {
            get {
                return ResourceManager.GetString("TextBoxAppsBrowsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while applying the selected themes, we disabled theme switching.
        /// </summary>
        public static string themeApplyError {
            get {
                return ResourceManager.GetString("themeApplyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme:.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your themes.
        /// </summary>
        public static string ThemeHeaderCreate {
            get {
                return ResourceManager.GetString("ThemeHeaderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your themes.
        /// </summary>
        public static string ThemeHeaderPick {
            get {
                return ResourceManager.GetString("ThemeHeaderPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme:.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Theme (more features).
        /// </summary>
        public static string ThemeSelectionTheme {
            get {
                return ResourceManager.GetString("ThemeSelectionTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Wallpaper (recommended).
        /// </summary>
        public static string ThemeSelectionWallaper {
            get {
                return ResourceManager.GetString("ThemeSelectionWallaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string ThemeTutorialStep {
            get {
                return ResourceManager.GetString("ThemeTutorialStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open Windows Theme settings..
        /// </summary>
        public static string ThemeTutorialStep1 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now set the Windows colour under Colours to white for the light theme. Select your favorite Wallpaper, Mouse Cursor and Accent Color..
        /// </summary>
        public static string ThemeTutorialStep2 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to theme settings and save your theme..
        /// </summary>
        public static string ThemeTutorialStep3 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the process for the dark theme..
        /// </summary>
        public static string ThemeTutorialStep4 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Dark Mode.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These options are disabled while using a Windows Theme. 
        ///You can set this individually up in your Windows Theme..
        /// </summary>
        public static string ToolTipDisabledDueTheme {
            get {
                return ResourceManager.GetString("ToolTipDisabledDueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string updateButton {
            get {
                return ResourceManager.GetString("updateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we check at every program start for updates..
        /// </summary>
        public static string updateInfoText {
            get {
                return ResourceManager.GetString("updateInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string userFeedback {
            get {
                return ResourceManager.GetString("userFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate the checkbox to enable automatic theme switching.
        /// </summary>
        public static string welcomeText {
            get {
                return ResourceManager.GetString("welcomeText", resourceCulture);
            }
        }
    }
}
