//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoThemeChanger.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoThemeChanger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string applyButton {
            get {
                return ResourceManager.GetString("applyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable automatic theme switching 的本地化字符串。
        /// </summary>
        public static string autoCheckBox {
            get {
                return ResourceManager.GetString("autoCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 hour clock 的本地化字符串。
        /// </summary>
        public static string cb12HourTime {
            get {
                return ResourceManager.GetString("cb12HourTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only visible in dark mode 的本地化字符串。
        /// </summary>
        public static string cbAccentColor {
            get {
                return ResourceManager.GetString("cbAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search for updates in background 的本地化字符串。
        /// </summary>
        public static string cbBackgroundUpdate {
            get {
                return ResourceManager.GetString("cbBackgroundUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This option is disabled, because you haven&apos;t installed the Windows 10 April 2019 Update on your machine. 的本地化字符串。
        /// </summary>
        public static string cmb1903 {
            get {
                return ResourceManager.GetString("cmb1903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accent Color for Taskbar 的本地化字符串。
        /// </summary>
        public static string cmbAccentColor {
            get {
                return ResourceManager.GetString("cmbAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust to theme 的本地化字符串。
        /// </summary>
        public static string cmbAdjTheme {
            get {
                return ResourceManager.GetString("cmbAdjTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always dark 的本地化字符串。
        /// </summary>
        public static string cmbAlwDark {
            get {
                return ResourceManager.GetString("cmbAlwDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always white 的本地化字符串。
        /// </summary>
        public static string cmbAlwWhite {
            get {
                return ResourceManager.GetString("cmbAlwWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently: 的本地化字符串。
        /// </summary>
        public static string dbCurrently {
            get {
                return ResourceManager.GetString("dbCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallpaper for dark theme 的本地化字符串。
        /// </summary>
        public static string dbDark {
            get {
                return ResourceManager.GetString("dbDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete/Disable 的本地化字符串。
        /// </summary>
        public static string dbDel {
            get {
                return ResourceManager.GetString("dbDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maybe your picture file is corrupted or the path doesn&apos;t exist. 的本地化字符串。
        /// </summary>
        public static string dbErrorText {
            get {
                return ResourceManager.GetString("dbErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick file 的本地化字符串。
        /// </summary>
        public static string dbFilePicker {
            get {
                return ResourceManager.GetString("dbFilePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallpaper for light theme 的本地化字符串。
        /// </summary>
        public static string dbLight {
            get {
                return ResourceManager.GetString("dbLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop Background 的本地化字符串。
        /// </summary>
        public static string dbMainHeader {
            get {
                return ResourceManager.GetString("dbMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pictures 的本地化字符串。
        /// </summary>
        public static string dbPictures {
            get {
                return ResourceManager.GetString("dbPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We couldn&apos;t generate a preview of your image, sorry! 的本地化字符串。
        /// </summary>
        public static string dbPreviewError {
            get {
                return ResourceManager.GetString("dbPreviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We couldn&apos;t save your settings, sorry! 的本地化字符串。
        /// </summary>
        public static string dbSavedError {
            get {
                return ResourceManager.GetString("dbSavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select two wallpaper 的本地化字符串。
        /// </summary>
        public static string dbSaveToolTip {
            get {
                return ResourceManager.GetString("dbSaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select an image 的本地化字符串。
        /// </summary>
        public static string dbSelectImage {
            get {
                return ResourceManager.GetString("dbSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Desktop Background 的本地化字符串。
        /// </summary>
        public static string dbTitle {
            get {
                return ResourceManager.GetString("dbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 use current background 的本地化字符串。
        /// </summary>
        public static string dbUseCurrent {
            get {
                return ResourceManager.GetString("dbUseCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable features for Windows 1903 的本地化字符串。
        /// </summary>
        public static string debugModeCheckBox {
            get {
                return ResourceManager.GetString("debugModeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error has occured 的本地化字符串。
        /// </summary>
        public static string errorOcurredTitle {
            get {
                return ResourceManager.GetString("errorOcurredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apps: 的本地化字符串。
        /// </summary>
        public static string lblApps {
            get {
                return ResourceManager.GetString("lblApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author: Armin Osaj © 2019 的本地化字符串。
        /// </summary>
        public static string lblAuthor {
            get {
                return ResourceManager.GetString("lblAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 City 的本地化字符串。
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom start time 的本地化字符串。
        /// </summary>
        public static string lblCustomStart {
            get {
                return ResourceManager.GetString("lblCustomStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string lblDark {
            get {
                return ResourceManager.GetString("lblDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark theme 的本地化字符串。
        /// </summary>
        public static string lblDarkTheme {
            get {
                return ResourceManager.GetString("lblDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edge: 的本地化字符串。
        /// </summary>
        public static string lblEdge {
            get {
                return ResourceManager.GetString("lblEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language: 的本地化字符串。
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string lblLight {
            get {
                return ResourceManager.GetString("lblLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light theme 的本地化字符串。
        /// </summary>
        public static string lblLightTheme {
            get {
                return ResourceManager.GetString("lblLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch current theme 的本地化字符串。
        /// </summary>
        public static string lblSwitchTheme {
            get {
                return ResourceManager.GetString("lblSwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System: 的本地化字符串。
        /// </summary>
        public static string lblSystem {
            get {
                return ResourceManager.GetString("lblSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Used third party software 的本地化字符串。
        /// </summary>
        public static string lblThirdParty {
            get {
                return ResourceManager.GetString("lblThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translator: Armin Osaj 的本地化字符串。
        /// </summary>
        public static string lblTranslator {
            get {
                return ResourceManager.GetString("lblTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates 的本地化字符串。
        /// </summary>
        public static string lblUpdates {
            get {
                return ResourceManager.GetString("lblUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Location Service 的本地化字符串。
        /// </summary>
        public static string locationCheckBox {
            get {
                return ResourceManager.GetString("locationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 changes were saved! 的本地化字符串。
        /// </summary>
        public static string msgChangesSaved {
            get {
                return ResourceManager.GetString("msgChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click on apply to save changes 的本地化字符串。
        /// </summary>
        public static string msgClickApply {
            get {
                return ResourceManager.GetString("msgClickApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string msgClose {
            get {
                return ResourceManager.GetString("msgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download update 的本地化字符串。
        /// </summary>
        public static string msgDownloadUpd {
            get {
                return ResourceManager.GetString("msgDownloadUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error occurred :( 的本地化字符串。
        /// </summary>
        public static string msgErrorOcc {
            get {
                return ResourceManager.GetString("msgErrorOcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The App needs permission to location 的本地化字符串。
        /// </summary>
        public static string msgLocPerm {
            get {
                return ResourceManager.GetString("msgLocPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string msgNo {
            get {
                return ResourceManager.GetString("msgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no new updates are available. 的本地化字符串。
        /// </summary>
        public static string msgNoUpd {
            get {
                return ResourceManager.GetString("msgNoUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching your location... 的本地化字符串。
        /// </summary>
        public static string msgSearchLoc {
            get {
                return ResourceManager.GetString("msgSearchLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 searching for update... 的本地化字符串。
        /// </summary>
        public static string msgSearchUpd {
            get {
                return ResourceManager.GetString("msgSearchUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: We couldn&apos;t read your current theme. 的本地化字符串。
        /// </summary>
        public static string msgThemeError {
            get {
                return ResourceManager.GetString("msgThemeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 a new update is available! 的本地化字符串。
        /// </summary>
        public static string msgUpdateAvail {
            get {
                return ResourceManager.GetString("msgUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thank you for using Auto Dark Mode!
        ///
        ///A new version is available on GitHub with fixes and enhancements.
        ///Do you want to download it?
        ///
        ///Currently installed version: {0}, new version: {1} 的本地化字符串。
        /// </summary>
        public static string msgUpdaterText {
            get {
                return ResourceManager.GetString("msgUpdaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string MsgYes {
            get {
                return ResourceManager.GetString("MsgYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 or 的本地化字符串。
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App restart needed to see the changes 的本地化字符串。
        /// </summary>
        public static string restartNeeded {
            get {
                return ResourceManager.GetString("restartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Dark Mode 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates 的本地化字符串。
        /// </summary>
        public static string updateButton {
            get {
                return ResourceManager.GetString("updateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 we check at every program start for updates. 的本地化字符串。
        /// </summary>
        public static string updateInfoText {
            get {
                return ResourceManager.GetString("updateInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        public static string userFeedback {
            get {
                return ResourceManager.GetString("userFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activate the checkbox to enable automatic theme switching 的本地化字符串。
        /// </summary>
        public static string welcomeText {
            get {
                return ResourceManager.GetString("welcomeText", resourceCulture);
            }
        }
    }
}
