version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directories:
      - "/AutoDarkMode*"
    schedule:
      interval: weekly
