files:
  - source: /AutoDarkModeLib/Properties/Resources.*.resx
    ignore:
      - Resources.Designer.cs
      - Resources.cs
    translation: '%original_path%/Resources.%two_letters_code%.%file_extension%'
