REM inject custom old files
echo System.Diagnostics.EventLog.Messages.dll>> bin\Publish\Updater\whitelist.txt
echo clrcompression.dll>> bin\Publish\Updater\whitelist.txt
echo AutoDarkModeConfig.dll>> bin\Publish\Updater\whitelist.txt
echo AutoDarkModeConfig.pdb>> bin\Publish\Updater\whitelist.txt
echo zh-tw>> bin\Publish\Updater\whitelist.txt
echo zh>> bin\Publish\Updater\whitelist.txt
echo mscordaccore>> bin\Publish\Updater\whitelist.txt
echo api-ms-win>> bin\Publish\Updater\whitelist.txt
echo dbgshim.dll>> bin\Publish\Updater\whitelist.txt
echo ucrtbase.dll>> bin\Publish\Updater\whitelist.txt
echo ThemeDll.dll>> bin\Publish\Updater\whitelist.txt
echo IThemeManager2Bridge>> bin\Publish\Updater\whitelist.txt
echo overrides.json>> bin\Publish\Updater\whitelist.txt
echo CoreMessagingXP.dll>> bin\Publish\Updater\whitelist.txt
echo cy-GB>> bin\Publish\Updater\whitelist.txt
echo dcompi.dll>> bin\Publish\Updater\whitelist.txt
echo dwmcorei.dll>> bin\Publish\Updater\whitelist.txt
echo DwmSceneI.dll>> bin\Publish\Updater\whitelist.txt
echo DWriteCore.dll>> bin\Publish\Updater\whitelist.txt
echo en-us>> bin\Publish\Updater\whitelist.txt
echo marshal.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.DirectManipulation.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Foundation.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Graphics.Display.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Graphics.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.InputStateManager.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.InteractiveExperiences.Projection.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Internal.FrameworkUdk.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.UI.Composition.OSSupport.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.UI.Input.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.UI.Text.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.UI.Windowing.Core.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.UI.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.UI.Xaml>> bin\Publish\Updater\whitelist.txt
echo Microsoft.UI.Xaml.Controls.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.UI.Xaml.Controls.pri>> bin\Publish\Updater\whitelist.txt
echo Microsoft.ui.xaml.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.UI.Xaml.Internal.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.UI.Xaml.Phone.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.ui.xaml.resources.19h1.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.ui.xaml.resources.common.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.UI.Xaml.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Web.WebView2.Core.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Web.WebView2.Core.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.ApplicationModel.DynamicDependency.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.ApplicationModel.Resources.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.ApplicationModel.Resources.Projection.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.ApplicationModel.Resources.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.ApplicationModel.WindowsAppRuntime.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.AppLifecycle.Projection.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.AppLifecycle.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.AppNotifications.Builder.Projection.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.AppNotifications.Builder.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.AppNotifications.Projection.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.AppNotifications.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.PushNotifications.Projection.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.PushNotifications.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.Security.AccessControl.Projection.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.Security.AccessControl.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.System.Power.Projection.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.System.Power.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.System.Projection.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.System.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.Widgets.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.Widgets.Projection.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.Windows.Widgets.winmd>> bin\Publish\Updater\whitelist.txt
echo Microsoft.WindowsAppRuntime.Bootstrap.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.WindowsAppRuntime.Bootstrap.Net.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.WindowsAppRuntime.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.WindowsAppRuntime.Insights.Resource.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.WindowsAppRuntime.Release.Net.dll>> bin\Publish\Updater\whitelist.txt
echo Microsoft.WinUI.dll>> bin\Publish\Updater\whitelist.txt
echo MRM.dll>> bin\Publish\Updater\whitelist.txt
echo PushNotificationsLongRunningTask.ProxyStub.dll>> bin\Publish\Updater\whitelist.txt
echo sr-Cyrl-RS>> bin\Publish\Updater\whitelist.txt
echo WindowsAppRuntime.png>> bin\Publish\Updater\whitelist.txt
echo WindowsAppSdk.AppxDeploymentExtensions.Desktop.dll>> bin\Publish\Updater\whitelist.txt
echo WinUIEdit.dll>> bin\Publish\Updater\whitelist.txt
echo wuceffectsi.dll>> bin\Publish\Updater\whitelist.txt
