//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDarkModeSvc.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoDarkModeSvc.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic theme switch.
        /// </summary>
        public static string AutomaticThemeSwitch {
            get {
                return ResourceManager.GetString("AutomaticThemeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable automatic switch.
        /// </summary>
        public static string DisableAutomaticSwitch {
            get {
                return ResourceManager.GetString("DisableAutomaticSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to disable auto switching instead?.
        /// </summary>
        public static string Msg_PauseActionDisableQuestion {
            get {
                return ResourceManager.GetString("Msg_PauseActionDisableQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic switching will also resume if you return to your previous theme..
        /// </summary>
        public static string Msg_PauseActionNotification {
            get {
                return ResourceManager.GetString("Msg_PauseActionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme switching paused until.
        /// </summary>
        public static string Msg_PauseHeader {
            get {
                return ResourceManager.GetString("Msg_PauseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme switching is paused once!.
        /// </summary>
        public static string Msg_PauseOnce {
            get {
                return ResourceManager.GetString("Msg_PauseOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to switch now or delay further?.
        /// </summary>
        public static string Msg_PendingQuestion {
            get {
                return ResourceManager.GetString("Msg_PendingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto theme switching resumed.
        /// </summary>
        public static string Msg_ResumeHeader {
            get {
                return ResourceManager.GetString("Msg_ResumeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme switch pending.
        /// </summary>
        public static string Msg_SwitchPending {
            get {
                return ResourceManager.GetString("Msg_SwitchPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        public static string PostponeTime_120 {
            get {
                return ResourceManager.GetString("PostponeTime_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes.
        /// </summary>
        public static string PostponeTime_15 {
            get {
                return ResourceManager.GetString("PostponeTime_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 hours.
        /// </summary>
        public static string PostponeTime_180 {
            get {
                return ResourceManager.GetString("PostponeTime_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        public static string PostponeTime_30 {
            get {
                return ResourceManager.GetString("PostponeTime_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 hours.
        /// </summary>
        public static string PostponeTime_360 {
            get {
                return ResourceManager.GetString("PostponeTime_360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string PostponeTime_60 {
            get {
                return ResourceManager.GetString("PostponeTime_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 hours.
        /// </summary>
        public static string PostponeTime_720 {
            get {
                return ResourceManager.GetString("PostponeTime_720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to request a theme switch immediately..
        /// </summary>
        public static string RequestSwitchAction {
            get {
                return ResourceManager.GetString("RequestSwitchAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert this action by clicking on the undo button below..
        /// </summary>
        public static string RevertAction {
            get {
                return ResourceManager.GetString("RevertAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch now.
        /// </summary>
        public static string SwitchNow {
            get {
                return ResourceManager.GetString("SwitchNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Automatic theme switch.
        /// </summary>
        public static string TrayMenuItem_AutomaticThemeSwitch {
            get {
                return ResourceManager.GetString("TrayMenuItem_AutomaticThemeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        public static string TrayMenuItem_Close {
            get {
                return ResourceManager.GetString("TrayMenuItem_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force &amp;Dark Theme.
        /// </summary>
        public static string TrayMenuItem_ForceDarkTheme {
            get {
                return ResourceManager.GetString("TrayMenuItem_ForceDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force &amp;Light Theme.
        /// </summary>
        public static string TrayMenuItem_ForceLightTheme {
            get {
                return ResourceManager.GetString("TrayMenuItem_ForceLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Config Directory.
        /// </summary>
        public static string TrayMenuItem_OpenConfigDir {
            get {
                return ResourceManager.GetString("TrayMenuItem_OpenConfigDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause auto switch.
        /// </summary>
        public static string TrayMenuItem_ThemeSwitchPause {
            get {
                return ResourceManager.GetString("TrayMenuItem_ThemeSwitchPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Toggle theme.
        /// </summary>
        public static string TrayMenuItem_ToggleTheme {
            get {
                return ResourceManager.GetString("TrayMenuItem_ToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to fix the theme.
        /// </summary>
        public static string TrayMenuItem_TryFixTheme {
            get {
                return ResourceManager.GetString("TrayMenuItem_TryFixTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until next sunrise.
        /// </summary>
        public static string UntilSunrise {
            get {
                return ResourceManager.GetString("UntilSunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until next sunset.
        /// </summary>
        public static string UntilSunset {
            get {
                return ResourceManager.GetString("UntilSunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while patching..
        /// </summary>
        public static string UpdateToast_AnErrorOccuredPatching {
            get {
                return ResourceManager.GetString("UpdateToast_AnErrorOccuredPatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downgrade.
        /// </summary>
        public static string UpdateToast_ButtonDowngrade {
            get {
                return ResourceManager.GetString("UpdateToast_ButtonDowngrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log directory.
        /// </summary>
        public static string UpdateToast_ButtonOpenLogDirectory {
            get {
                return ResourceManager.GetString("UpdateToast_ButtonOpenLogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpone.
        /// </summary>
        public static string UpdateToast_ButtonPostpone {
            get {
                return ResourceManager.GetString("UpdateToast_ButtonPostpone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateToast_ButtonUpdate {
            get {
                return ResourceManager.GetString("UpdateToast_ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string UpdateToast_CurrentVersion {
            get {
                return ResourceManager.GetString("UpdateToast_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downgrade {0} available.
        /// </summary>
        public static string UpdateToast_DowngradeAvailable {
            get {
                return ResourceManager.GetString("UpdateToast_DowngradeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downgrading to.
        /// </summary>
        public static string UpdateToast_DowngradingTo {
            get {
                return ResourceManager.GetString("UpdateToast_DowngradingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading….
        /// </summary>
        public static string UpdateToast_Downloading {
            get {
                return ResourceManager.GetString("UpdateToast_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download in progress.
        /// </summary>
        public static string UpdateToast_DownloadInProgress {
            get {
                return ResourceManager.GetString("UpdateToast_DownloadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to download page.
        /// </summary>
        public static string UpdateToast_GoToDownloadPage {
            get {
                return ResourceManager.GetString("UpdateToast_GoToDownloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string UpdateToast_Message {
            get {
                return ResourceManager.GetString("UpdateToast_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version {0} available.
        /// </summary>
        public static string UpdateToast_NewVersionAvailable {
            get {
                return ResourceManager.GetString("UpdateToast_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching failed.
        /// </summary>
        public static string UpdateToast_PatchingFailed {
            get {
                return ResourceManager.GetString("UpdateToast_PatchingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check service.log and updater.log for infos.
        /// </summary>
        public static string UpdateToast_SeeLogs {
            get {
                return ResourceManager.GetString("UpdateToast_SeeLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating to.
        /// </summary>
        public static string UpdateToast_UpgradingTo {
            get {
                return ResourceManager.GetString("UpdateToast_UpgradingTo", resourceCulture);
            }
        }
    }
}
