//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDarkModeSvc.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoDarkModeSvc.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic theme switch 的本地化字符串。
        /// </summary>
        public static string AutomaticThemeSwitch {
            get {
                return ResourceManager.GetString("AutomaticThemeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay 的本地化字符串。
        /// </summary>
        public static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable automatic switch 的本地化字符串。
        /// </summary>
        public static string DisableAutomaticSwitch {
            get {
                return ResourceManager.GetString("DisableAutomaticSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to disable auto switching instead? 的本地化字符串。
        /// </summary>
        public static string Msg_PauseActionDisableQuestion {
            get {
                return ResourceManager.GetString("Msg_PauseActionDisableQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic switching will also resume if you return to your previous theme. 的本地化字符串。
        /// </summary>
        public static string Msg_PauseActionNotification {
            get {
                return ResourceManager.GetString("Msg_PauseActionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme switching paused until 的本地化字符串。
        /// </summary>
        public static string Msg_PauseHeader {
            get {
                return ResourceManager.GetString("Msg_PauseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme switching is paused once! 的本地化字符串。
        /// </summary>
        public static string Msg_PauseOnce {
            get {
                return ResourceManager.GetString("Msg_PauseOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to switch now or delay further? 的本地化字符串。
        /// </summary>
        public static string Msg_PendingQuestion {
            get {
                return ResourceManager.GetString("Msg_PendingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto theme switching resumed 的本地化字符串。
        /// </summary>
        public static string Msg_ResumeHeader {
            get {
                return ResourceManager.GetString("Msg_ResumeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme switch pending 的本地化字符串。
        /// </summary>
        public static string Msg_SwitchPending {
            get {
                return ResourceManager.GetString("Msg_SwitchPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paused 的本地化字符串。
        /// </summary>
        public static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 hours 的本地化字符串。
        /// </summary>
        public static string PostponeTime_120 {
            get {
                return ResourceManager.GetString("PostponeTime_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 15 minutes 的本地化字符串。
        /// </summary>
        public static string PostponeTime_15 {
            get {
                return ResourceManager.GetString("PostponeTime_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 hours 的本地化字符串。
        /// </summary>
        public static string PostponeTime_180 {
            get {
                return ResourceManager.GetString("PostponeTime_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30 minutes 的本地化字符串。
        /// </summary>
        public static string PostponeTime_30 {
            get {
                return ResourceManager.GetString("PostponeTime_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 hours 的本地化字符串。
        /// </summary>
        public static string PostponeTime_360 {
            get {
                return ResourceManager.GetString("PostponeTime_360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 hour 的本地化字符串。
        /// </summary>
        public static string PostponeTime_60 {
            get {
                return ResourceManager.GetString("PostponeTime_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 hours 的本地化字符串。
        /// </summary>
        public static string PostponeTime_720 {
            get {
                return ResourceManager.GetString("PostponeTime_720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm to request a theme switch immediately. 的本地化字符串。
        /// </summary>
        public static string RequestSwitchAction {
            get {
                return ResourceManager.GetString("RequestSwitchAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Revert this action by clicking on the undo button below. 的本地化字符串。
        /// </summary>
        public static string RevertAction {
            get {
                return ResourceManager.GetString("RevertAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch now 的本地化字符串。
        /// </summary>
        public static string SwitchNow {
            get {
                return ResourceManager.GetString("SwitchNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Automatic theme switch 的本地化字符串。
        /// </summary>
        public static string TrayMenuItem_AutomaticThemeSwitch {
            get {
                return ResourceManager.GetString("TrayMenuItem_AutomaticThemeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Close 的本地化字符串。
        /// </summary>
        public static string TrayMenuItem_Close {
            get {
                return ResourceManager.GetString("TrayMenuItem_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force &amp;Dark Theme 的本地化字符串。
        /// </summary>
        public static string TrayMenuItem_ForceDarkTheme {
            get {
                return ResourceManager.GetString("TrayMenuItem_ForceDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force &amp;Light Theme 的本地化字符串。
        /// </summary>
        public static string TrayMenuItem_ForceLightTheme {
            get {
                return ResourceManager.GetString("TrayMenuItem_ForceLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Open Config Directory 的本地化字符串。
        /// </summary>
        public static string TrayMenuItem_OpenConfigDir {
            get {
                return ResourceManager.GetString("TrayMenuItem_OpenConfigDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Pause auto switch 的本地化字符串。
        /// </summary>
        public static string TrayMenuItem_ThemeSwitchPause {
            get {
                return ResourceManager.GetString("TrayMenuItem_ThemeSwitchPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Toggle theme 的本地化字符串。
        /// </summary>
        public static string TrayMenuItem_ToggleTheme {
            get {
                return ResourceManager.GetString("TrayMenuItem_ToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to fix the theme 的本地化字符串。
        /// </summary>
        public static string TrayMenuItem_TryFixTheme {
            get {
                return ResourceManager.GetString("TrayMenuItem_TryFixTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 until 的本地化字符串。
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 until next sunrise 的本地化字符串。
        /// </summary>
        public static string UntilSunrise {
            get {
                return ResourceManager.GetString("UntilSunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 until next sunset 的本地化字符串。
        /// </summary>
        public static string UntilSunset {
            get {
                return ResourceManager.GetString("UntilSunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while patching. 的本地化字符串。
        /// </summary>
        public static string UpdateToast_AnErrorOccuredPatching {
            get {
                return ResourceManager.GetString("UpdateToast_AnErrorOccuredPatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downgrade 的本地化字符串。
        /// </summary>
        public static string UpdateToast_ButtonDowngrade {
            get {
                return ResourceManager.GetString("UpdateToast_ButtonDowngrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open log directory 的本地化字符串。
        /// </summary>
        public static string UpdateToast_ButtonOpenLogDirectory {
            get {
                return ResourceManager.GetString("UpdateToast_ButtonOpenLogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Postpone 的本地化字符串。
        /// </summary>
        public static string UpdateToast_ButtonPostpone {
            get {
                return ResourceManager.GetString("UpdateToast_ButtonPostpone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string UpdateToast_ButtonUpdate {
            get {
                return ResourceManager.GetString("UpdateToast_ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version 的本地化字符串。
        /// </summary>
        public static string UpdateToast_CurrentVersion {
            get {
                return ResourceManager.GetString("UpdateToast_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downgrade {0} available 的本地化字符串。
        /// </summary>
        public static string UpdateToast_DowngradeAvailable {
            get {
                return ResourceManager.GetString("UpdateToast_DowngradeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downgrading to 的本地化字符串。
        /// </summary>
        public static string UpdateToast_DowngradingTo {
            get {
                return ResourceManager.GetString("UpdateToast_DowngradingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading… 的本地化字符串。
        /// </summary>
        public static string UpdateToast_Downloading {
            get {
                return ResourceManager.GetString("UpdateToast_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download in progress 的本地化字符串。
        /// </summary>
        public static string UpdateToast_DownloadInProgress {
            get {
                return ResourceManager.GetString("UpdateToast_DownloadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to download page 的本地化字符串。
        /// </summary>
        public static string UpdateToast_GoToDownloadPage {
            get {
                return ResourceManager.GetString("UpdateToast_GoToDownloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string UpdateToast_Message {
            get {
                return ResourceManager.GetString("UpdateToast_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version {0} available 的本地化字符串。
        /// </summary>
        public static string UpdateToast_NewVersionAvailable {
            get {
                return ResourceManager.GetString("UpdateToast_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patching failed 的本地化字符串。
        /// </summary>
        public static string UpdateToast_PatchingFailed {
            get {
                return ResourceManager.GetString("UpdateToast_PatchingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check service.log and updater.log for infos 的本地化字符串。
        /// </summary>
        public static string UpdateToast_SeeLogs {
            get {
                return ResourceManager.GetString("UpdateToast_SeeLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating to 的本地化字符串。
        /// </summary>
        public static string UpdateToast_UpgradingTo {
            get {
                return ResourceManager.GetString("UpdateToast_UpgradingTo", resourceCulture);
            }
        }
    }
}
