//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDarkModeApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoDarkModeApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string applyButton {
            get {
                return ResourceManager.GetString("applyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Coordinates.
        /// </summary>
        public static string applyGeoButton {
            get {
                return ResourceManager.GetString("applyGeoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic theme switching.
        /// </summary>
        public static string autoCheckBox {
            get {
                return ResourceManager.GetString("autoCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Extension.
        /// </summary>
        public static string buttonDownloadExtension {
            get {
                return ResourceManager.GetString("buttonDownloadExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 hour clock.
        /// </summary>
        public static string cb12HourTime {
            get {
                return ResourceManager.GetString("cb12HourTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only visible in dark mode.
        ///If you run into issues: please increase the switching delay in settings. .
        /// </summary>
        public static string cbAccentColor {
            get {
                return ResourceManager.GetString("cbAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic update check.
        /// </summary>
        public static string cbBackgroundUpdate {
            get {
                return ResourceManager.GetString("cbBackgroundUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch after Connected Standby (not recommended).
        /// </summary>
        public static string cbConnectedStandby {
            get {
                return ResourceManager.GetString("cbConnectedStandby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile devices, like Microsoft Surface products, are using a new kind of standby mode.
        ///Enabling this option makes sure that Auto Dark Mode immediately switches the theme after waking up your computer.
        ///But it also reduces the battery life, so ONLY activate if necessary!.
        /// </summary>
        public static string cbConnectedStandbyTooltip {
            get {
                return ResourceManager.GetString("cbConnectedStandbyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative light theme.
        /// </summary>
        public static string cbOfficeWhiteTheme {
            get {
                return ResourceManager.GetString("cbOfficeWhiteTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable dark mode when device is unplugged.
        /// </summary>
        public static string cbSettingsBatteryDarkMode {
            get {
                return ResourceManager.GetString("cbSettingsBatteryDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use grayscale color filter (sends Win + Ctrl + C).
        /// </summary>
        public static string cbSettingsColourFilter {
            get {
                return ResourceManager.GetString("cbSettingsColourFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy saver mitigation for theme switch.
        /// </summary>
        public static string cbSettingsEnergySaverMitigation {
            get {
                return ResourceManager.GetString("cbSettingsEnergySaverMitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This only works if you haven&apos;t manually enabled battery saver!.
        /// </summary>
        public static string cbSettingsEnergySaverMitigationInfo {
            get {
                return ResourceManager.GetString("cbSettingsEnergySaverMitigationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use logon task instead of startup entry.
        /// </summary>
        public static string cbSettingsLogonTask {
            get {
                return ResourceManager.GetString("cbSettingsLogonTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-User support.
        /// </summary>
        public static string cbSettingsMultiUserImprovements {
            get {
                return ResourceManager.GetString("cbSettingsMultiUserImprovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is disabled, because you haven&apos;t installed the Windows 10 April 2019 Update on your machine..
        /// </summary>
        public static string cmb1903 {
            get {
                return ResourceManager.GetString("cmb1903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color for Taskbar.
        /// </summary>
        public static string cmbAccentColor {
            get {
                return ResourceManager.GetString("cmbAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapt to system.
        /// </summary>
        public static string cmbAdjTheme {
            get {
                return ResourceManager.GetString("cmbAdjTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always dark.
        /// </summary>
        public static string cmbAlwDark {
            get {
                return ResourceManager.GetString("cmbAlwDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always light.
        /// </summary>
        public static string cmbAlwWhite {
            get {
                return ResourceManager.GetString("cmbAlwWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open config file.
        /// </summary>
        public static string ConfigHyperLinkOpenConfig {
            get {
                return ResourceManager.GetString("ConfigHyperLinkOpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open config folder.
        /// </summary>
        public static string ConfigHyperLinkOpenConfigFolder {
            get {
                return ResourceManager.GetString("ConfigHyperLinkOpenConfigFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log file.
        /// </summary>
        public static string ConfigHyperLinkOpenLog {
            get {
                return ResourceManager.GetString("ConfigHyperLinkOpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string ConfigTextBlockHeader {
            get {
                return ResourceManager.GetString("ConfigTextBlockHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently:.
        /// </summary>
        public static string dbCurrently {
            get {
                return ResourceManager.GetString("dbCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper for dark theme.
        /// </summary>
        public static string dbDark {
            get {
                return ResourceManager.GetString("dbDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete/Disable.
        /// </summary>
        public static string dbDel {
            get {
                return ResourceManager.GetString("dbDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe your picture file is corrupted or the path doesn&apos;t exist..
        /// </summary>
        public static string dbErrorText {
            get {
                return ResourceManager.GetString("dbErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick file.
        /// </summary>
        public static string dbFilePicker {
            get {
                return ResourceManager.GetString("dbFilePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper for light theme.
        /// </summary>
        public static string dbLight {
            get {
                return ResourceManager.GetString("dbLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Background.
        /// </summary>
        public static string dbMainHeader {
            get {
                return ResourceManager.GetString("dbMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string dbPictures {
            get {
                return ResourceManager.GetString("dbPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t generate a preview of your image, sorry!.
        /// </summary>
        public static string dbPreviewError {
            get {
                return ResourceManager.GetString("dbPreviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t save your settings, sorry!.
        /// </summary>
        public static string dbSavedError {
            get {
                return ResourceManager.GetString("dbSavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select two wallpapers.
        /// </summary>
        public static string dbSaveToolTip {
            get {
                return ResourceManager.GetString("dbSaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image.
        /// </summary>
        public static string dbSelectImage {
            get {
                return ResourceManager.GetString("dbSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Desktop Background.
        /// </summary>
        public static string dbTitle {
            get {
                return ResourceManager.GetString("dbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use current background.
        /// </summary>
        public static string dbUseCurrent {
            get {
                return ResourceManager.GetString("dbUseCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable features for Windows 1903.
        /// </summary>
        public static string debugModeCheckBox {
            get {
                return ResourceManager.GetString("debugModeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! Thank you for using Auto Dark Mode! Do you like it so far?
        ///
        ///This app makes your everyday more pleasant, by helping you take care of your eyes. At the same time it&apos;s completely free, ad-free, doesn&apos;t collect user data and it&apos;s open source.
        ///I don&apos;t generate any profit with this project.
        ///
        ///For this reason you could support me with a voluntary donation. Even a small amount makes me jumping happy through my apartment. Just donate as much as you value my work..
        /// </summary>
        public static string donationDescription {
            get {
                return ResourceManager.GetString("donationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why should you donate?.
        /// </summary>
        public static string DonationHeaderReason {
            get {
                return ResourceManager.GetString("DonationHeaderReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to donate?.
        /// </summary>
        public static string DonationHowTo {
            get {
                return ResourceManager.GetString("DonationHowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send me money via PayPal. It&apos;s completely voluntary and you shouldn&apos;t expect any compensation..
        /// </summary>
        public static string DonationPayPalDescription {
            get {
                return ResourceManager.GetString("DonationPayPalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We ran into the following issue:
        ///{0}
        ///
        ///We will now try to solve this problem by running an algorithm as administrator. Maybe this will help.
        ///Auto Dark Mode will restart afterwards and you&apos;ll need to re-apply your settings, sorry!
        ///
        ///Sidenote: NEVER run Auto Dark Mode as administrator manually!.
        /// </summary>
        public static string ErrorApplyRestart {
            get {
                return ResourceManager.GetString("ErrorApplyRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Your input is invalid.
        /// </summary>
        public static string errorNumberInput {
            get {
                return ResourceManager.GetString("errorNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        public static string errorOcurredTitle {
            get {
                return ResourceManager.GetString("errorOcurredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but we couldn&apos;t apply your settings.
        ///
        ///Here are some things you can try:
        ///- Restart the Auto Dark Mode service
        ///- Check if the service is running
        ///- Close the service, delete the config.yaml file and re-configue
        ///
        ///If these things didn&apos;t help, you can create an issue on GitHub. You can access the issue by clicking the &quot;Yes&quot; button..
        /// </summary>
        public static string errorThemeApply {
            get {
                return ResourceManager.GetString("errorThemeApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic coordinates.
        /// </summary>
        public static string headerGeoCoordinates {
            get {
                return ResourceManager.GetString("headerGeoCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location data.
        /// </summary>
        public static string headerLocationData {
            get {
                return ResourceManager.GetString("headerLocationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps:.
        /// </summary>
        public static string lblApps {
            get {
                return ResourceManager.GetString("lblApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom start time.
        /// </summary>
        public static string lblCustomStart {
            get {
                return ResourceManager.GetString("lblCustomStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string lblDark {
            get {
                return ResourceManager.GetString("lblDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        public static string lblDarkTheme {
            get {
                return ResourceManager.GetString("lblDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge (Legacy):.
        /// </summary>
        public static string lblEdge {
            get {
                return ResourceManager.GetString("lblEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string lblLight {
            get {
                return ResourceManager.GetString("lblLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        public static string lblLightTheme {
            get {
                return ResourceManager.GetString("lblLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Office 2013 - 2019:.
        /// </summary>
        public static string lblOffice {
            get {
                return ResourceManager.GetString("lblOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string lblOffset {
            get {
                return ResourceManager.GetString("lblOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a theme.
        /// </summary>
        public static string lblPickTheme {
            get {
                return ResourceManager.GetString("lblPickTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a wallpaper.
        /// </summary>
        public static string lblPickWallpaper {
            get {
                return ResourceManager.GetString("lblPickWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string lblReset {
            get {
                return ResourceManager.GetString("lblReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch current theme.
        /// </summary>
        public static string lblSwitchTheme {
            get {
                return ResourceManager.GetString("lblSwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System:.
        /// </summary>
        public static string lblSystem {
            get {
                return ResourceManager.GetString("lblSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used third party software.
        /// </summary>
        public static string lblThirdParty {
            get {
                return ResourceManager.GetString("lblThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator: Armin Osaj &amp; Samuel Schiegg.
        /// </summary>
        public static string lblTranslator {
            get {
                return ResourceManager.GetString("lblTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string lblUpdates {
            get {
                return ResourceManager.GetString("lblUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Location Service.
        /// </summary>
        public static string locationCheckBox {
            get {
                return ResourceManager.GetString("locationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string locationCityNotFound {
            get {
                return ResourceManager.GetString("locationCityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to a Windows bug, the taskbar doesn&apos;t properly switch its color in battery saver mode. Please turn off battery saver if you run into issues..
        /// </summary>
        public static string msgBatterySaver {
            get {
                return ResourceManager.GetString("msgBatterySaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes have been saved!.
        /// </summary>
        public static string msgChangesSaved {
            get {
                return ResourceManager.GetString("msgChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Apply to save changes..
        /// </summary>
        public static string msgClickApply {
            get {
                return ResourceManager.GetString("msgClickApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string msgClose {
            get {
                return ResourceManager.GetString("msgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download update.
        /// </summary>
        public static string msgDownloadUpd {
            get {
                return ResourceManager.GetString("msgDownloadUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error occurred :(.
        /// </summary>
        public static string msgErrorOcc {
            get {
                return ResourceManager.GetString("msgErrorOcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app needs access to your location.
        /// </summary>
        public static string msgLocPerm {
            get {
                return ResourceManager.GetString("msgLocPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string msgNo {
            get {
                return ResourceManager.GetString("msgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates are available..
        /// </summary>
        public static string msgNoUpd {
            get {
                return ResourceManager.GetString("msgNoUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching your location....
        /// </summary>
        public static string msgSearchLoc {
            get {
                return ResourceManager.GetString("msgSearchLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for updates....
        /// </summary>
        public static string msgSearchUpd {
            get {
                return ResourceManager.GetString("msgSearchUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: We couldn&apos;t read your current theme..
        /// </summary>
        public static string msgThemeError {
            get {
                return ResourceManager.GetString("msgThemeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update is available!.
        /// </summary>
        public static string msgUpdateAvail {
            get {
                return ResourceManager.GetString("msgUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using Auto Dark Mode!
        ///
        ///A new version is available on GitHub with fixes and enhancements.
        ///Do you want to install it?
        ///
        ///Currently installed version: {0}, new version: {1}.
        /// </summary>
        public static string msgUpdaterText {
            get {
                return ResourceManager.GetString("msgUpdaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MsgYes {
            get {
                return ResourceManager.GetString("MsgYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string NavbarAbout {
            get {
                return ResourceManager.GetString("NavbarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string NavbarApps {
            get {
                return ResourceManager.GetString("NavbarApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string NavbarDonation {
            get {
                return ResourceManager.GetString("NavbarDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string NavbarPersonalization {
            get {
                return ResourceManager.GetString("NavbarPersonalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavbarSettings {
            get {
                return ResourceManager.GetString("NavbarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Modes.
        /// </summary>
        public static string NavbarSwitchModes {
            get {
                return ResourceManager.GetString("NavbarSwitchModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string NavbarTime {
            get {
                return ResourceManager.GetString("NavbarTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string NavbarTitle {
            get {
                return ResourceManager.GetString("NavbarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper/Theme.
        /// </summary>
        public static string NavbarWallpaper {
            get {
                return ResourceManager.GetString("NavbarWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string offsetButton {
            get {
                return ResourceManager.GetString("offsetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenPath {
            get {
                return ResourceManager.GetString("OpenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set custom hours.
        /// </summary>
        public static string rbCustomHours {
            get {
                return ResourceManager.GetString("rbCustomHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string rbDisabled {
            get {
                return ResourceManager.GetString("rbDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From sunset to sunrise.
        /// </summary>
        public static string rbLocation {
            get {
                return ResourceManager.GetString("rbLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From sunset to sunrise (geographic coordinates).
        /// </summary>
        public static string rbLocationGeo {
            get {
                return ResourceManager.GetString("rbLocationGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App restart required to see changes.
        /// </summary>
        public static string restartNeeded {
            get {
                return ResourceManager.GetString("restartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay for switching taskbar colors (ms):.
        /// </summary>
        public static string SettingsAccentColorTimeout {
            get {
                return ResourceManager.GetString("SettingsAccentColorTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value for energy saver slider.
        /// </summary>
        public static string SettingsBatterySlider {
            get {
                return ResourceManager.GetString("SettingsBatterySlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide tray icon (not recommended).
        /// </summary>
        public static string SettingsCheckBoxHideTray {
            get {
                return ResourceManager.GetString("SettingsCheckBoxHideTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t switch while playing video games.
        /// </summary>
        public static string SwitchModesCheckBoxGPUMonitoring {
            get {
                return ResourceManager.GetString("SwitchModesCheckBoxGPUMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast (1 sample).
        /// </summary>
        public static string SwitchModesComboBoxItemSamplesFast {
            get {
                return ResourceManager.GetString("SwitchModesComboBoxItemSamplesFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium (2 samples).
        /// </summary>
        public static string SwitchModesComboBoxItemSamplesMedium {
            get {
                return ResourceManager.GetString("SwitchModesComboBoxItemSamplesMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow (3 samples).
        /// </summary>
        public static string SwitchModesComboBoxItemSamplesSlow {
            get {
                return ResourceManager.GetString("SwitchModesComboBoxItemSamplesSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU usage detection speed.
        /// </summary>
        public static string SwitchModesTextBlockGPUUsageDetectionSpeed {
            get {
                return ResourceManager.GetString("SwitchModesTextBlockGPUUsageDetectionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery powered devices.
        /// </summary>
        public static string SwitchModesTextBlockHeaderBatteryPowered {
            get {
                return ResourceManager.GetString("SwitchModesTextBlockHeaderBatteryPowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string SwitchModesTextBlockHeaderConditions {
            get {
                return ResourceManager.GetString("SwitchModesTextBlockHeaderConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum GPU usage to delay switching.
        /// </summary>
        public static string SwitchModesTextBlockMinimumUsage {
            get {
                return ResourceManager.GetString("SwitchModesTextBlockMinimumUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended tools.
        /// </summary>
        public static string tbAppsTitleRecommendedTools {
            get {
                return ResourceManager.GetString("tbAppsTitleRecommendedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This browser extension makes websites in Chrome, Firefox and Edge respect the system theme..
        /// </summary>
        public static string tbDarkReaderDescription {
            get {
                return ResourceManager.GetString("tbDarkReaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is disabled while theme mode is enabled..
        /// </summary>
        public static string tbFeatureDisabledWhileThemeMode {
            get {
                return ResourceManager.GetString("tbFeatureDisabledWhileThemeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is disabled while wallpaper mode is enabled..
        /// </summary>
        public static string tbFeatureDisabledWhileWallpaperMode {
            get {
                return ResourceManager.GetString("tbFeatureDisabledWhileWallpaperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo coordinates for your location.
        /// </summary>
        public static string tbGetCoordinates {
            get {
                return ResourceManager.GetString("tbGetCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help with a problem?.
        /// </summary>
        public static string tbHelp {
            get {
                return ResourceManager.GetString("tbHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers more features, but you need to set up a windows .theme file. Customize your desktop wallpaper per monitor, set a diashow, change your mouse cursor, set an accent color and individual sounds..
        /// </summary>
        public static string tbPickTheme {
            get {
                return ResourceManager.GetString("tbPickTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers less features, but is easier to set up. Customize your desktop wallpaper for all monitors, individual monitors or set a background color..
        /// </summary>
        public static string tbPickWallpaper {
            get {
                return ResourceManager.GetString("tbPickWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional delay for activating grayscale color filter:.
        /// </summary>
        public static string tbSettingsColourFilterDelay {
            get {
                return ResourceManager.GetString("tbSettingsColourFilterDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We check for new versions of Auto Dark Mode in the background. When an update is available, we will notify you via toast notification.
        /// </summary>
        public static string tbUpdates {
            get {
                return ResourceManager.GetString("tbUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while applying the selected themes, we disabled theme switching.
        /// </summary>
        public static string ThemeApplyError1 {
            get {
                return ResourceManager.GetString("ThemeApplyError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while applying a .theme-file. Maybe your created theme got deleted or moved. This is why we deactivated theme switching for now. To re-enable it, please open Auto Dark Mode and configure {0} Settings..
        /// </summary>
        public static string ThemeApplyError2 {
            get {
                return ResourceManager.GetString("ThemeApplyError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme:.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your themes.
        /// </summary>
        public static string ThemeHeaderCreate {
            get {
                return ResourceManager.GetString("ThemeHeaderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your themes.
        /// </summary>
        public static string ThemeHeaderPick {
            get {
                return ResourceManager.GetString("ThemeHeaderPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme:.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mode:.
        /// </summary>
        public static string ThemeSelection {
            get {
                return ResourceManager.GetString("ThemeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Theme (more features).
        /// </summary>
        public static string ThemeSelectionTheme {
            get {
                return ResourceManager.GetString("ThemeSelectionTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Wallpaper (recommended).
        /// </summary>
        public static string ThemeSelectionWallaper {
            get {
                return ResourceManager.GetString("ThemeSelectionWallaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string ThemeTutorialStep {
            get {
                return ResourceManager.GetString("ThemeTutorialStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open Windows Theme settings..
        /// </summary>
        public static string ThemeTutorialStep1 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now navigate to &apos;Colors&apos; and change the system color to &apos;Light&apos; for the light theme. Select your favorite Wallpaper, Mouse Cursor and Accent Color..
        /// </summary>
        public static string ThemeTutorialStep2 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to theme settings and save your theme..
        /// </summary>
        public static string ThemeTutorialStep3 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat this process for the dark theme..
        /// </summary>
        public static string ThemeTutorialStep4 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Dark Mode.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These options are disabled while using a Windows Theme.
        ///You can set them up individually in your Windows Theme..
        /// </summary>
        public static string ToolTipDisabledDueTheme {
            get {
                return ResourceManager.GetString("ToolTipDisabledDueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string updateButton {
            get {
                return ResourceManager.GetString("updateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We check for updates at every program start..
        /// </summary>
        public static string updateInfoText {
            get {
                return ResourceManager.GetString("updateInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically download and install new versions.
        /// </summary>
        public static string UpdatesCheckBoxAutoInstall {
            get {
                return ResourceManager.GetString("UpdatesCheckBoxAutoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show notifications.
        /// </summary>
        public static string UpdatesCheckBoxSilent {
            get {
                return ResourceManager.GetString("UpdatesCheckBoxSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select update channel.
        /// </summary>
        public static string UpdatesCheckBoxUpdateChannel {
            get {
                return ResourceManager.GetString("UpdatesCheckBoxUpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates when Auto Dark Mode starts.
        /// </summary>
        public static string UpdatesComboBoxAtStart {
            get {
                return ResourceManager.GetString("UpdatesComboBoxAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 days.
        /// </summary>
        public static string UpdatesComboBoxInterval14 {
            get {
                return ResourceManager.GetString("UpdatesComboBoxInterval14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 days.
        /// </summary>
        public static string UpdatesComboBoxInterval3 {
            get {
                return ResourceManager.GetString("UpdatesComboBoxInterval3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        public static string UpdatesComboBoxInterval7 {
            get {
                return ResourceManager.GetString("UpdatesComboBoxInterval7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last checked.
        /// </summary>
        public static string UpdatesTextBlockLastChecked {
            get {
                return ResourceManager.GetString("UpdatesTextBlockLastChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        public static string UpdatesTextBlockLastCheckedNever {
            get {
                return ResourceManager.GetString("UpdatesTextBlockLastCheckedNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change how often we check for updates.
        /// </summary>
        public static string UpdatesTextBlockUpdateInterval {
            get {
                return ResourceManager.GetString("UpdatesTextBlockUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string userFeedback {
            get {
                return ResourceManager.GetString("userFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string WallpaperComboBoxItemDark {
            get {
                return ResourceManager.GetString("WallpaperComboBoxItemDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        public static string WallpaperComboBoxItemLight {
            get {
                return ResourceManager.GetString("WallpaperComboBoxItemLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string WallpaperComboBoxItemPicture {
            get {
                return ResourceManager.GetString("WallpaperComboBoxItemPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture (multiple monitors).
        /// </summary>
        public static string WallpaperComboBoxItemPictureMM {
            get {
                return ResourceManager.GetString("WallpaperComboBoxItemPictureMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid color.
        /// </summary>
        public static string WallpaperComboBoxItemSolidColor {
            get {
                return ResourceManager.GetString("WallpaperComboBoxItemSolidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string WallpaperComboBoxMode {
            get {
                return ResourceManager.GetString("WallpaperComboBoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string WallpaperComboBoxMonitor {
            get {
                return ResourceManager.GetString("WallpaperComboBoxMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string WallpaperComboBoxType {
            get {
                return ResourceManager.GetString("WallpaperComboBoxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove disconnected monitors.
        /// </summary>
        public static string WallpaperHyperLinkRemoveDisconnected {
            get {
                return ResourceManager.GetString("WallpaperHyperLinkRemoveDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper.
        /// </summary>
        public static string WallpaperTextBlockHeader {
            get {
                return ResourceManager.GetString("WallpaperTextBlockHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string WallpaperTextBlockHeaderColor {
            get {
                return ResourceManager.GetString("WallpaperTextBlockHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex code.
        /// </summary>
        public static string WallpaperTextBoxHeaderHex {
            get {
                return ResourceManager.GetString("WallpaperTextBoxHeaderHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable wallpaper switch.
        /// </summary>
        public static string WallpaperToggleSwitch {
            get {
                return ResourceManager.GetString("WallpaperToggleSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate the checkbox to enable automatic theme switching.
        /// </summary>
        public static string welcomeText {
            get {
                return ResourceManager.GetString("welcomeText", resourceCulture);
            }
        }
    }
}
