//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDarkModeApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoDarkModeApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string applyButton {
            get {
                return ResourceManager.GetString("applyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic theme switching.
        /// </summary>
        internal static string autoCheckBox {
            get {
                return ResourceManager.GetString("autoCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Extension.
        /// </summary>
        internal static string buttonDownloadExtension {
            get {
                return ResourceManager.GetString("buttonDownloadExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 hour clock.
        /// </summary>
        internal static string cb12HourTime {
            get {
                return ResourceManager.GetString("cb12HourTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only visible in dark mode.
        ///If you run into issues: please increase the switching delay in settings. .
        /// </summary>
        internal static string cbAccentColor {
            get {
                return ResourceManager.GetString("cbAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for updates in background.
        /// </summary>
        internal static string cbBackgroundUpdate {
            get {
                return ResourceManager.GetString("cbBackgroundUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch after Connected Standby (not recommended).
        /// </summary>
        internal static string cbConnectedStandby {
            get {
                return ResourceManager.GetString("cbConnectedStandby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile devices, like Microsoft Surface products, are using a new kind of standby mode. 
        ///Enabling this option makes sure that Auto Dark Mode immediately switches the theme after waking up your computer. 
        ///But it also reduces the battery life, so ONLY activate if necessary!.
        /// </summary>
        internal static string cbConnectedStandbyTooltip {
            get {
                return ResourceManager.GetString("cbConnectedStandbyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative light theme.
        /// </summary>
        internal static string cbOfficeWhiteTheme {
            get {
                return ResourceManager.GetString("cbOfficeWhiteTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use grayscale color filter (sends Win + Ctrl + C).
        /// </summary>
        internal static string cbSettingsColourFilter {
            get {
                return ResourceManager.GetString("cbSettingsColourFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Logon Task instead of Autostart entry.
        /// </summary>
        internal static string cbSettingsLogonTask {
            get {
                return ResourceManager.GetString("cbSettingsLogonTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-User support.
        /// </summary>
        internal static string cbSettingsMultiUserImprovements {
            get {
                return ResourceManager.GetString("cbSettingsMultiUserImprovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is disabled, because you haven&apos;t installed the Windows 10 April 2019 Update on your machine..
        /// </summary>
        internal static string cmb1903 {
            get {
                return ResourceManager.GetString("cmb1903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color for Taskbar.
        /// </summary>
        internal static string cmbAccentColor {
            get {
                return ResourceManager.GetString("cmbAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapt to system.
        /// </summary>
        internal static string cmbAdjTheme {
            get {
                return ResourceManager.GetString("cmbAdjTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always dark.
        /// </summary>
        internal static string cmbAlwDark {
            get {
                return ResourceManager.GetString("cmbAlwDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always light.
        /// </summary>
        internal static string cmbAlwWhite {
            get {
                return ResourceManager.GetString("cmbAlwWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently:.
        /// </summary>
        internal static string dbCurrently {
            get {
                return ResourceManager.GetString("dbCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper for dark theme.
        /// </summary>
        internal static string dbDark {
            get {
                return ResourceManager.GetString("dbDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete/Disable.
        /// </summary>
        internal static string dbDel {
            get {
                return ResourceManager.GetString("dbDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe your picture file is corrupted or the path doesn&apos;t exist..
        /// </summary>
        internal static string dbErrorText {
            get {
                return ResourceManager.GetString("dbErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick file.
        /// </summary>
        internal static string dbFilePicker {
            get {
                return ResourceManager.GetString("dbFilePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper for light theme.
        /// </summary>
        internal static string dbLight {
            get {
                return ResourceManager.GetString("dbLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Background.
        /// </summary>
        internal static string dbMainHeader {
            get {
                return ResourceManager.GetString("dbMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string dbPictures {
            get {
                return ResourceManager.GetString("dbPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t generate a preview of your image, sorry!.
        /// </summary>
        internal static string dbPreviewError {
            get {
                return ResourceManager.GetString("dbPreviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t save your settings, sorry!.
        /// </summary>
        internal static string dbSavedError {
            get {
                return ResourceManager.GetString("dbSavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select two wallpapers.
        /// </summary>
        internal static string dbSaveToolTip {
            get {
                return ResourceManager.GetString("dbSaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image.
        /// </summary>
        internal static string dbSelectImage {
            get {
                return ResourceManager.GetString("dbSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Desktop Background.
        /// </summary>
        internal static string dbTitle {
            get {
                return ResourceManager.GetString("dbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use current background.
        /// </summary>
        internal static string dbUseCurrent {
            get {
                return ResourceManager.GetString("dbUseCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable features for Windows 1903.
        /// </summary>
        internal static string debugModeCheckBox {
            get {
                return ResourceManager.GetString("debugModeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! Thank you for using Auto Dark Mode! Do you like it so far?
        ///
        ///This app makes your everyday more pleasant, by helping you take care of your eyes. At the same time it&apos;s completely free, ad-free, doesn&apos;t collect user data and it&apos;s open source.
        ///I don&apos;t generate any profit with this project.
        ///
        ///For this reason you could support me with a voluntary donation. Even a small amount makes me jumping happy through my apartment. Just donate as much as you value my work..
        /// </summary>
        internal static string donationDescription {
            get {
                return ResourceManager.GetString("donationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why should you donate?.
        /// </summary>
        internal static string DonationHeaderReason {
            get {
                return ResourceManager.GetString("DonationHeaderReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to donate?.
        /// </summary>
        internal static string DonationHowTo {
            get {
                return ResourceManager.GetString("DonationHowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send me money via PayPal. It&apos;s completely voluntary and you shouldn&apos;t expect any compensation..
        /// </summary>
        internal static string DonationPayPalDescription {
            get {
                return ResourceManager.GetString("DonationPayPalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We ran into the following issue: 
        ///{0}
        ///
        ///We will now try to solve this problem by running an algorithm as administrator. Maybe this will help. 
        ///Auto Dark Mode will restart afterwards and you&apos;ll need to re-apply your settings, sorry!
        ///
        ///Sidenote: NEVER run Auto Dark Mode as administrator manually!.
        /// </summary>
        internal static string ErrorApplyRestart {
            get {
                return ResourceManager.GetString("ErrorApplyRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Your input is invalid.
        /// </summary>
        internal static string errorNumberInput {
            get {
                return ResourceManager.GetString("errorNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        internal static string errorOcurredTitle {
            get {
                return ResourceManager.GetString("errorOcurredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but we couldn&apos;t apply your settings.
        ///
        ///Here are some things you can try:
        ///- Uninstall and then reinstall auto dark mode.
        ///- Try to disable {0} in the Auto Dark Mode settings.
        ///- If you enabled Desktop Wallpaper, disable the feature and try again.
        ///
        ///If these things didn&apos;t help, you can comment the GitHub issue with posting a screenshot of your error. You can access the issue by clicking the &quot;Yes&quot; button..
        /// </summary>
        internal static string errorThemeApply {
            get {
                return ResourceManager.GetString("errorThemeApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps:.
        /// </summary>
        internal static string lblApps {
            get {
                return ResourceManager.GetString("lblApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom start time.
        /// </summary>
        internal static string lblCustomStart {
            get {
                return ResourceManager.GetString("lblCustomStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string lblDark {
            get {
                return ResourceManager.GetString("lblDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        internal static string lblDarkTheme {
            get {
                return ResourceManager.GetString("lblDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge (Legacy):.
        /// </summary>
        internal static string lblEdge {
            get {
                return ResourceManager.GetString("lblEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string lblLight {
            get {
                return ResourceManager.GetString("lblLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        internal static string lblLightTheme {
            get {
                return ResourceManager.GetString("lblLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string lblOffset {
            get {
                return ResourceManager.GetString("lblOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string lblReset {
            get {
                return ResourceManager.GetString("lblReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch current theme.
        /// </summary>
        internal static string lblSwitchTheme {
            get {
                return ResourceManager.GetString("lblSwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System:.
        /// </summary>
        internal static string lblSystem {
            get {
                return ResourceManager.GetString("lblSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used third party software.
        /// </summary>
        internal static string lblThirdParty {
            get {
                return ResourceManager.GetString("lblThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator: Armin Osaj.
        /// </summary>
        internal static string lblTranslator {
            get {
                return ResourceManager.GetString("lblTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string lblUpdates {
            get {
                return ResourceManager.GetString("lblUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Location Service.
        /// </summary>
        internal static string locationCheckBox {
            get {
                return ResourceManager.GetString("locationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string locationCityNotFound {
            get {
                return ResourceManager.GetString("locationCityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to a Windows bug, the taskbar doesn&apos;t properly switch its color in battery saver mode. Please turn off battery saver if you run into issues..
        /// </summary>
        internal static string msgBatterySaver {
            get {
                return ResourceManager.GetString("msgBatterySaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes have been saved!.
        /// </summary>
        internal static string msgChangesSaved {
            get {
                return ResourceManager.GetString("msgChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Apply to save changes..
        /// </summary>
        internal static string msgClickApply {
            get {
                return ResourceManager.GetString("msgClickApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string msgClose {
            get {
                return ResourceManager.GetString("msgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download update.
        /// </summary>
        internal static string msgDownloadUpd {
            get {
                return ResourceManager.GetString("msgDownloadUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error occurred :(.
        /// </summary>
        internal static string msgErrorOcc {
            get {
                return ResourceManager.GetString("msgErrorOcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app needs access to your location.
        /// </summary>
        internal static string msgLocPerm {
            get {
                return ResourceManager.GetString("msgLocPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string msgNo {
            get {
                return ResourceManager.GetString("msgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates are available..
        /// </summary>
        internal static string msgNoUpd {
            get {
                return ResourceManager.GetString("msgNoUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching your location....
        /// </summary>
        internal static string msgSearchLoc {
            get {
                return ResourceManager.GetString("msgSearchLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for updates....
        /// </summary>
        internal static string msgSearchUpd {
            get {
                return ResourceManager.GetString("msgSearchUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: We couldn&apos;t read your current theme..
        /// </summary>
        internal static string msgThemeError {
            get {
                return ResourceManager.GetString("msgThemeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update is available!.
        /// </summary>
        internal static string msgUpdateAvail {
            get {
                return ResourceManager.GetString("msgUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using Auto Dark Mode!
        ///
        ///A new version is available on GitHub with fixes and enhancements.
        ///Do you want to download it?
        ///
        ///Currently installed version: {0}, new version: {1}.
        /// </summary>
        internal static string msgUpdaterText {
            get {
                return ResourceManager.GetString("msgUpdaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MsgYes {
            get {
                return ResourceManager.GetString("MsgYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string NavbarAbout {
            get {
                return ResourceManager.GetString("NavbarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        internal static string NavbarApps {
            get {
                return ResourceManager.GetString("NavbarApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string NavbarDonation {
            get {
                return ResourceManager.GetString("NavbarDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string NavbarSettings {
            get {
                return ResourceManager.GetString("NavbarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string NavbarTime {
            get {
                return ResourceManager.GetString("NavbarTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string NavbarTitle {
            get {
                return ResourceManager.GetString("NavbarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper/Theme.
        /// </summary>
        internal static string NavbarWallpaper {
            get {
                return ResourceManager.GetString("NavbarWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string offsetButton {
            get {
                return ResourceManager.GetString("offsetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string OpenPath {
            get {
                return ResourceManager.GetString("OpenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set custom hours.
        /// </summary>
        internal static string rbCustomHours {
            get {
                return ResourceManager.GetString("rbCustomHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From sunset to sunrise.
        /// </summary>
        internal static string rbLocation {
            get {
                return ResourceManager.GetString("rbLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App restart required to see changes.
        /// </summary>
        internal static string restartNeeded {
            get {
                return ResourceManager.GetString("restartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay for switching taskbar colors (ms):.
        /// </summary>
        internal static string SettingsAccentColorTimeout {
            get {
                return ResourceManager.GetString("SettingsAccentColorTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended tools.
        /// </summary>
        internal static string tbAppsTitleRecommendedTools {
            get {
                return ResourceManager.GetString("tbAppsTitleRecommendedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This browser extension makes websites in Chrome, Firefox and Edge respect the system theme..
        /// </summary>
        internal static string tbDarkReaderDescription {
            get {
                return ResourceManager.GetString("tbDarkReaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help with a problem?.
        /// </summary>
        internal static string tbHelp {
            get {
                return ResourceManager.GetString("tbHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional delay for activating grayscale color filter:.
        /// </summary>
        internal static string tbSettingsColourFilterDelay {
            get {
                return ResourceManager.GetString("tbSettingsColourFilterDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while applying the selected themes, we disabled theme switching.
        /// </summary>
        internal static string ThemeApplyError1 {
            get {
                return ResourceManager.GetString("ThemeApplyError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while applying a .theme-file. Maybe your created theme got deleted or moved. This is why we deactivated theme switching for now. To re-enable it, please open Auto Dark Mode and configure {0} Settings..
        /// </summary>
        internal static string ThemeApplyError2 {
            get {
                return ResourceManager.GetString("ThemeApplyError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme:.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your themes.
        /// </summary>
        internal static string ThemeHeaderCreate {
            get {
                return ResourceManager.GetString("ThemeHeaderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your themes.
        /// </summary>
        internal static string ThemeHeaderPick {
            get {
                return ResourceManager.GetString("ThemeHeaderPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme:.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mode:.
        /// </summary>
        internal static string ThemeSelection {
            get {
                return ResourceManager.GetString("ThemeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Theme (more features).
        /// </summary>
        internal static string ThemeSelectionTheme {
            get {
                return ResourceManager.GetString("ThemeSelectionTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Wallpaper (recommended).
        /// </summary>
        internal static string ThemeSelectionWallaper {
            get {
                return ResourceManager.GetString("ThemeSelectionWallaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string ThemeTutorialStep {
            get {
                return ResourceManager.GetString("ThemeTutorialStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open Windows Theme settings..
        /// </summary>
        internal static string ThemeTutorialStep1 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now navigate to &apos;Colors&apos; and change the system color to &apos;Light&apos; for the light theme. Select your favorite Wallpaper, Mouse Cursor and Accent Color..
        /// </summary>
        internal static string ThemeTutorialStep2 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to theme settings and save your theme..
        /// </summary>
        internal static string ThemeTutorialStep3 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat this process for the dark theme..
        /// </summary>
        internal static string ThemeTutorialStep4 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Dark Mode.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These options are disabled while using a Windows Theme. 
        ///You can set them up individually in your Windows Theme..
        /// </summary>
        internal static string ToolTipDisabledDueTheme {
            get {
                return ResourceManager.GetString("ToolTipDisabledDueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string updateButton {
            get {
                return ResourceManager.GetString("updateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We check for updates at every program start..
        /// </summary>
        internal static string updateInfoText {
            get {
                return ResourceManager.GetString("updateInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string userFeedback {
            get {
                return ResourceManager.GetString("userFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download later.
        /// </summary>
        internal static string VersionXUpdaterButtonLater {
            get {
                return ResourceManager.GetString("VersionXUpdaterButtonLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never remind me again.
        /// </summary>
        internal static string VersionXUpdaterButtonNever {
            get {
                return ResourceManager.GetString("VersionXUpdaterButtonNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download now.
        /// </summary>
        internal static string VersionXUpdaterButtonNow {
            get {
                return ResourceManager.GetString("VersionXUpdaterButtonNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the last couple of months we&apos;ve been working hard to provide you the best update possible. Now it&apos;s here!
        ///
        ///Auto Dark Mode X has been completely rewritten from scratch. It now features a real background task instead of relying on Windows Task Scheduler. This means you get a more reliable and more flexible theme switching experience!
        ///
        ///Yes, this consumes more resources in the background, but in return we offer you more features, to enhance your productivity. For example:
        ///- Game Mode: disable theme swit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VersionXUpdaterDescription {
            get {
                return ResourceManager.GetString("VersionXUpdaterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Dark Mode X is available.
        /// </summary>
        internal static string VersionXUpdaterHeader {
            get {
                return ResourceManager.GetString("VersionXUpdaterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version X is a great, big update that you should definitely try out! Are you sure you DON&apos;T want to download it? We will never remind you again!.
        /// </summary>
        internal static string VersionXUpdaterNeverDescription {
            get {
                return ResourceManager.GetString("VersionXUpdaterNeverDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string VersionXUpdaterNeverTitle {
            get {
                return ResourceManager.GetString("VersionXUpdaterNeverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate the checkbox to enable automatic theme switching.
        /// </summary>
        internal static string welcomeText {
            get {
                return ResourceManager.GetString("welcomeText", resourceCulture);
            }
        }
    }
}
