//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDarkModeConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoDarkModeConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Copy.
        /// </summary>
        public static string AboutButtonCopy {
            get {
                return ResourceManager.GetString("AboutButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Follow us.
        /// </summary>
        public static string AboutTextBlockFollowUs {
            get {
                return ResourceManager.GetString("AboutTextBlockFollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Version.
        /// </summary>
        public static string AboutTextBlockVersion {
            get {
                return ResourceManager.GetString("AboutTextBlockVersion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Apply.
        /// </summary>
        public static string applyButton {
            get {
                return ResourceManager.GetString("applyButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Apply Coordinates.
        /// </summary>
        public static string applyGeoButton {
            get {
                return ResourceManager.GetString("applyGeoButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use Taskbar Accent Color during.
        /// </summary>
        public static string AppsTextBlockAdaptiveTaskbarAccent {
            get {
                return ResourceManager.GetString("AppsTextBlockAdaptiveTaskbarAccent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Accent only.
        /// </summary>
        public static string AppSystemComboBoxItemAccentOnly {
            get {
                return ResourceManager.GetString("AppSystemComboBoxItemAccentOnly", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enable automatic theme switching.
        /// </summary>
        public static string autoCheckBox {
            get {
                return ResourceManager.GetString("autoCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Download Extension.
        /// </summary>
        public static string buttonDownloadExtension {
            get {
                return ResourceManager.GetString("buttonDownloadExtension", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 12 hour clock.
        /// </summary>
        public static string cb12HourTime {
            get {
                return ResourceManager.GetString("cb12HourTime", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Only visible in dark mode.
        ///If you run into issues: please increase the switching delay in settings. .
        /// </summary>
        public static string cbAccentColor {
            get {
                return ResourceManager.GetString("cbAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Automatic update check.
        /// </summary>
        public static string cbBackgroundUpdate {
            get {
                return ResourceManager.GetString("cbBackgroundUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Switch after Connected Standby (not recommended).
        /// </summary>
        public static string cbConnectedStandby {
            get {
                return ResourceManager.GetString("cbConnectedStandby", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mobile devices, like Microsoft Surface products, are using a new kind of standby mode.
        ///Enabling this option makes sure that Auto Dark Mode immediately switches the theme after waking up your computer.
        ///But it also reduces the battery life, so ONLY activate if necessary!.
        /// </summary>
        public static string cbConnectedStandbyTooltip {
            get {
                return ResourceManager.GetString("cbConnectedStandbyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Alternative light theme.
        /// </summary>
        public static string cbOfficeWhiteTheme {
            get {
                return ResourceManager.GetString("cbOfficeWhiteTheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enable dark mode when device is unplugged.
        /// </summary>
        public static string cbSettingsBatteryDarkMode {
            get {
                return ResourceManager.GetString("cbSettingsBatteryDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use color filter (sends Win + Ctrl + C).
        /// </summary>
        public static string cbSettingsColourFilter {
            get {
                return ResourceManager.GetString("cbSettingsColourFilter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Energy saver mitigation for theme switch.
        /// </summary>
        public static string cbSettingsEnergySaverMitigation {
            get {
                return ResourceManager.GetString("cbSettingsEnergySaverMitigation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This only works if you haven&apos;t manually enabled battery saver!.
        /// </summary>
        public static string cbSettingsEnergySaverMitigationInfo {
            get {
                return ResourceManager.GetString("cbSettingsEnergySaverMitigationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use logon task instead of startup entry.
        /// </summary>
        public static string cbSettingsLogonTask {
            get {
                return ResourceManager.GetString("cbSettingsLogonTask", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Multi-User support.
        /// </summary>
        public static string cbSettingsMultiUserImprovements {
            get {
                return ResourceManager.GetString("cbSettingsMultiUserImprovements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This option is disabled, because you haven&apos;t installed the Windows 10 April 2019 Update on your machine..
        /// </summary>
        public static string cmb1903 {
            get {
                return ResourceManager.GetString("cmb1903", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Accent Color for Taskbar.
        /// </summary>
        public static string cmbAccentColor {
            get {
                return ResourceManager.GetString("cmbAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adapt to system.
        /// </summary>
        public static string cmbAdjTheme {
            get {
                return ResourceManager.GetString("cmbAdjTheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Always dark.
        /// </summary>
        public static string cmbAlwDark {
            get {
                return ResourceManager.GetString("cmbAlwDark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Always light.
        /// </summary>
        public static string cmbAlwWhite {
            get {
                return ResourceManager.GetString("cmbAlwWhite", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open config file.
        /// </summary>
        public static string ConfigHyperLinkOpenConfig {
            get {
                return ResourceManager.GetString("ConfigHyperLinkOpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open config folder.
        /// </summary>
        public static string ConfigHyperLinkOpenConfigFolder {
            get {
                return ResourceManager.GetString("ConfigHyperLinkOpenConfigFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open log file.
        /// </summary>
        public static string ConfigHyperLinkOpenLog {
            get {
                return ResourceManager.GetString("ConfigHyperLinkOpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Config.
        /// </summary>
        public static string ConfigTextBlockHeader {
            get {
                return ResourceManager.GetString("ConfigTextBlockHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Currently:.
        /// </summary>
        public static string dbCurrently {
            get {
                return ResourceManager.GetString("dbCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wallpaper for dark theme.
        /// </summary>
        public static string dbDark {
            get {
                return ResourceManager.GetString("dbDark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete/Disable.
        /// </summary>
        public static string dbDel {
            get {
                return ResourceManager.GetString("dbDel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maybe your picture file is corrupted or the path doesn&apos;t exist..
        /// </summary>
        public static string dbErrorText {
            get {
                return ResourceManager.GetString("dbErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pick file.
        /// </summary>
        public static string dbFilePicker {
            get {
                return ResourceManager.GetString("dbFilePicker", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wallpaper for light theme.
        /// </summary>
        public static string dbLight {
            get {
                return ResourceManager.GetString("dbLight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Desktop Background.
        /// </summary>
        public static string dbMainHeader {
            get {
                return ResourceManager.GetString("dbMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pictures.
        /// </summary>
        public static string dbPictures {
            get {
                return ResourceManager.GetString("dbPictures", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu We couldn&apos;t generate a preview of your image, sorry!.
        /// </summary>
        public static string dbPreviewError {
            get {
                return ResourceManager.GetString("dbPreviewError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu We couldn&apos;t save your settings, sorry!.
        /// </summary>
        public static string dbSavedError {
            get {
                return ResourceManager.GetString("dbSavedError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select two wallpapers.
        /// </summary>
        public static string dbSaveToolTip {
            get {
                return ResourceManager.GetString("dbSaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select an image.
        /// </summary>
        public static string dbSelectImage {
            get {
                return ResourceManager.GetString("dbSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Configure Desktop Background.
        /// </summary>
        public static string dbTitle {
            get {
                return ResourceManager.GetString("dbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu use current background.
        /// </summary>
        public static string dbUseCurrent {
            get {
                return ResourceManager.GetString("dbUseCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enable features for Windows 1903.
        /// </summary>
        public static string debugModeCheckBox {
            get {
                return ResourceManager.GetString("debugModeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Disabled.
        /// </summary>
        public static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hello! Thank you for using Auto Dark Mode! Do you like it so far?
        ///
        ///This app makes your everyday more pleasant, by helping you take care of your eyes. At the same time it&apos;s completely free, ad-free, doesn&apos;t collect user data and it&apos;s open source.
        ///I don&apos;t generate any profit with this project.
        ///
        ///For this reason you could support me with a voluntary donation. Even a small amount makes me jumping happy through my apartment. Just donate as much as you value my work..
        /// </summary>
        public static string donationDescription {
            get {
                return ResourceManager.GetString("donationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Why should you donate?.
        /// </summary>
        public static string DonationHeaderReason {
            get {
                return ResourceManager.GetString("DonationHeaderReason", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu How to donate?.
        /// </summary>
        public static string DonationHowTo {
            get {
                return ResourceManager.GetString("DonationHowTo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You can send me money via PayPal. It&apos;s completely voluntary and you shouldn&apos;t expect any compensation..
        /// </summary>
        public static string DonationPayPalDescription {
            get {
                return ResourceManager.GetString("DonationPayPalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enabled.
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu We ran into the following issue:
        ///{0}
        ///
        ///We will now try to solve this problem by running an algorithm as administrator. Maybe this will help.
        ///Auto Dark Mode will restart afterwards and you&apos;ll need to re-apply your settings, sorry!
        ///
        ///Sidenote: NEVER run Auto Dark Mode as administrator manually!.
        /// </summary>
        public static string ErrorApplyRestart {
            get {
                return ResourceManager.GetString("ErrorApplyRestart", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error: Your input is invalid.
        /// </summary>
        public static string errorNumberInput {
            get {
                return ResourceManager.GetString("errorNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occured.
        /// </summary>
        public static string errorOcurredTitle {
            get {
                return ResourceManager.GetString("errorOcurredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sorry, but we couldn&apos;t apply your settings.
        ///
        ///Here are some things you can try:
        ///- Restart the Auto Dark Mode service
        ///- Check if the service is running
        ///- Close the service, delete the config.yaml file and re-configue
        ///
        ///If these things didn&apos;t help, you can create an issue on GitHub. You can access the issue by clicking the &quot;Yes&quot; button..
        /// </summary>
        public static string errorThemeApply {
            get {
                return ResourceManager.GetString("errorThemeApply", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Geographic coordinates.
        /// </summary>
        public static string headerGeoCoordinates {
            get {
                return ResourceManager.GetString("headerGeoCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Location data.
        /// </summary>
        public static string headerLocationData {
            get {
                return ResourceManager.GetString("headerLocationData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Apps:.
        /// </summary>
        public static string lblApps {
            get {
                return ResourceManager.GetString("lblApps", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Custom start time.
        /// </summary>
        public static string lblCustomStart {
            get {
                return ResourceManager.GetString("lblCustomStart", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dark.
        /// </summary>
        public static string lblDark {
            get {
                return ResourceManager.GetString("lblDark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dark theme.
        /// </summary>
        public static string lblDarkTheme {
            get {
                return ResourceManager.GetString("lblDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edge (Legacy):.
        /// </summary>
        public static string lblEdge {
            get {
                return ResourceManager.GetString("lblEdge", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Language:.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light.
        /// </summary>
        public static string lblLight {
            get {
                return ResourceManager.GetString("lblLight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light theme.
        /// </summary>
        public static string lblLightTheme {
            get {
                return ResourceManager.GetString("lblLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Microsoft Office 2013 - 2019:.
        /// </summary>
        public static string lblOffice {
            get {
                return ResourceManager.GetString("lblOffice", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Offset.
        /// </summary>
        public static string lblOffset {
            get {
                return ResourceManager.GetString("lblOffset", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pick a theme.
        /// </summary>
        public static string lblPickTheme {
            get {
                return ResourceManager.GetString("lblPickTheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pick a wallpaper.
        /// </summary>
        public static string lblPickWallpaper {
            get {
                return ResourceManager.GetString("lblPickWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Position.
        /// </summary>
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reset.
        /// </summary>
        public static string lblReset {
            get {
                return ResourceManager.GetString("lblReset", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        public static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Switch current theme.
        /// </summary>
        public static string lblSwitchTheme {
            get {
                return ResourceManager.GetString("lblSwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu System:.
        /// </summary>
        public static string lblSystem {
            get {
                return ResourceManager.GetString("lblSystem", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Used third party software.
        /// </summary>
        public static string lblThirdParty {
            get {
                return ResourceManager.GetString("lblThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Translator: Armin Osaj &amp; Samuel Schiegg.
        /// </summary>
        public static string lblTranslator {
            get {
                return ResourceManager.GetString("lblTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Updates.
        /// </summary>
        public static string lblUpdates {
            get {
                return ResourceManager.GetString("lblUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use Location Service.
        /// </summary>
        public static string locationCheckBox {
            get {
                return ResourceManager.GetString("locationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Not found.
        /// </summary>
        public static string locationCityNotFound {
            get {
                return ResourceManager.GetString("locationCityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Due to a Windows bug, the taskbar doesn&apos;t properly switch its color in battery saver mode. Please turn off battery saver if you run into issues..
        /// </summary>
        public static string msgBatterySaver {
            get {
                return ResourceManager.GetString("msgBatterySaver", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your changes have been saved!.
        /// </summary>
        public static string msgChangesSaved {
            get {
                return ResourceManager.GetString("msgChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Click Apply to save changes..
        /// </summary>
        public static string msgClickApply {
            get {
                return ResourceManager.GetString("msgClickApply", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Close.
        /// </summary>
        public static string msgClose {
            get {
                return ResourceManager.GetString("msgClose", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Download update.
        /// </summary>
        public static string msgDownloadUpd {
            get {
                return ResourceManager.GetString("msgDownloadUpd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu error occurred :(.
        /// </summary>
        public static string msgErrorOcc {
            get {
                return ResourceManager.GetString("msgErrorOcc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This app needs access to your location.
        /// </summary>
        public static string msgLocPerm {
            get {
                return ResourceManager.GetString("msgLocPerm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No.
        /// </summary>
        public static string msgNo {
            get {
                return ResourceManager.GetString("msgNo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No new updates are available..
        /// </summary>
        public static string msgNoUpd {
            get {
                return ResourceManager.GetString("msgNoUpd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Getting your location....
        /// </summary>
        public static string msgSearchLoc {
            get {
                return ResourceManager.GetString("msgSearchLoc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Looking for updates....
        /// </summary>
        public static string msgSearchUpd {
            get {
                return ResourceManager.GetString("msgSearchUpd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warning: We couldn&apos;t read your current theme..
        /// </summary>
        public static string msgThemeError {
            get {
                return ResourceManager.GetString("msgThemeError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu A new update is available!.
        /// </summary>
        public static string msgUpdateAvail {
            get {
                return ResourceManager.GetString("msgUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Thank you for using Auto Dark Mode!
        ///
        ///A new version is available on GitHub with fixes and enhancements.
        ///Do you want to install it?
        ///
        ///Currently installed version: {0}, new version: {1}.
        /// </summary>
        public static string msgUpdaterText {
            get {
                return ResourceManager.GetString("msgUpdaterText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Yes.
        /// </summary>
        public static string MsgYes {
            get {
                return ResourceManager.GetString("MsgYes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu About.
        /// </summary>
        public static string NavbarAbout {
            get {
                return ResourceManager.GetString("NavbarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Apps.
        /// </summary>
        public static string NavbarApps {
            get {
                return ResourceManager.GetString("NavbarApps", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Donate.
        /// </summary>
        public static string NavbarDonation {
            get {
                return ResourceManager.GetString("NavbarDonation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Personalization.
        /// </summary>
        public static string NavbarPersonalization {
            get {
                return ResourceManager.GetString("NavbarPersonalization", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        public static string NavbarSettings {
            get {
                return ResourceManager.GetString("NavbarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Switch Modes.
        /// </summary>
        public static string NavbarSwitchModes {
            get {
                return ResourceManager.GetString("NavbarSwitchModes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Time.
        /// </summary>
        public static string NavbarTime {
            get {
                return ResourceManager.GetString("NavbarTime", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Menu.
        /// </summary>
        public static string NavbarTitle {
            get {
                return ResourceManager.GetString("NavbarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Set.
        /// </summary>
        public static string offsetButton {
            get {
                return ResourceManager.GetString("offsetButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open Folder.
        /// </summary>
        public static string OpenPath {
            get {
                return ResourceManager.GetString("OpenPath", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Set custom hours.
        /// </summary>
        public static string rbCustomHours {
            get {
                return ResourceManager.GetString("rbCustomHours", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Disabled.
        /// </summary>
        public static string rbDisabled {
            get {
                return ResourceManager.GetString("rbDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu From sunset to sunrise.
        /// </summary>
        public static string rbLocation {
            get {
                return ResourceManager.GetString("rbLocation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu From sunset to sunrise (geographic coordinates).
        /// </summary>
        public static string rbLocationGeo {
            get {
                return ResourceManager.GetString("rbLocationGeo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Restart.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu App restart required to see changes.
        /// </summary>
        public static string restartNeeded {
            get {
                return ResourceManager.GetString("restartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delay for switching taskbar colors (ms):.
        /// </summary>
        public static string SettingsAccentColorTimeout {
            get {
                return ResourceManager.GetString("SettingsAccentColorTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Default value for energy saver slider.
        /// </summary>
        public static string SettingsBatterySlider {
            get {
                return ResourceManager.GetString("SettingsBatterySlider", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hide tray icon (not recommended).
        /// </summary>
        public static string SettingsCheckBoxHideTray {
            get {
                return ResourceManager.GetString("SettingsCheckBoxHideTray", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start Auto Dark Mode with Windows.
        /// </summary>
        public static string SettingsPageAutostartDescription {
            get {
                return ResourceManager.GetString("SettingsPageAutostartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Autostart.
        /// </summary>
        public static string SettingsPageAutostartHeader {
            get {
                return ResourceManager.GetString("SettingsPageAutostartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mode:.
        /// </summary>
        public static string SettingsPageAutostartMode {
            get {
                return ResourceManager.GetString("SettingsPageAutostartMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Disabled.
        /// </summary>
        public static string SettingsPageAutostartModeDisabled {
            get {
                return ResourceManager.GetString("SettingsPageAutostartModeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu None.
        /// </summary>
        public static string SettingsPageAutostartModeNone {
            get {
                return ResourceManager.GetString("SettingsPageAutostartModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Not found.
        /// </summary>
        public static string SettingsPageAutostartModeNotFound {
            get {
                return ResourceManager.GetString("SettingsPageAutostartModeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Registry Key.
        /// </summary>
        public static string SettingsPageAutostartModeRegistry {
            get {
                return ResourceManager.GetString("SettingsPageAutostartModeRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Task.
        /// </summary>
        public static string SettingsPageAutostartModeTask {
            get {
                return ResourceManager.GetString("SettingsPageAutostartModeTask", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Path:.
        /// </summary>
        public static string SettingsPageAutostartPath {
            get {
                return ResourceManager.GetString("SettingsPageAutostartPath", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Refresh Autostart.
        /// </summary>
        public static string SettingsPageAutostartRefreshButton {
            get {
                return ResourceManager.GetString("SettingsPageAutostartRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Language.
        /// </summary>
        public static string SettingsPageLanguageSectionTitle {
            get {
                return ResourceManager.GetString("SettingsPageLanguageSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Restart App.
        /// </summary>
        public static string SettingsPageRestartButton {
            get {
                return ResourceManager.GetString("SettingsPageRestartButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You have disabled the auto start entry via Windows..
        /// </summary>
        public static string SettingsPageWindowsAutostartDisabled {
            get {
                return ResourceManager.GetString("SettingsPageWindowsAutostartDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Service not running yet, please wait....
        /// </summary>
        public static string StartupLaunchingServiceText {
            get {
                return ResourceManager.GetString("StartupLaunchingServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Launching Service.
        /// </summary>
        public static string StartupLaunchingServiceTitle {
            get {
                return ResourceManager.GetString("StartupLaunchingServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The service is not responding. Please check if AutoDarkModeSvc.exe is running, and try again!.
        /// </summary>
        public static string StartupServiceUnresponsive {
            get {
                return ResourceManager.GetString("StartupServiceUnresponsive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Don&apos;t switch while playing video games.
        /// </summary>
        public static string SwitchModesCheckBoxGPUMonitoring {
            get {
                return ResourceManager.GetString("SwitchModesCheckBoxGPUMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fast (1 sample).
        /// </summary>
        public static string SwitchModesComboBoxItemSamplesFast {
            get {
                return ResourceManager.GetString("SwitchModesComboBoxItemSamplesFast", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Medium (2 samples).
        /// </summary>
        public static string SwitchModesComboBoxItemSamplesMedium {
            get {
                return ResourceManager.GetString("SwitchModesComboBoxItemSamplesMedium", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Slow (3 samples).
        /// </summary>
        public static string SwitchModesComboBoxItemSamplesSlow {
            get {
                return ResourceManager.GetString("SwitchModesComboBoxItemSamplesSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only edit hotkeys while they are disabled..
        /// </summary>
        public static string SwitchModesHotkeyEditHint {
            get {
                return ResourceManager.GetString("SwitchModesHotkeyEditHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU usage detection speed.
        /// </summary>
        public static string SwitchModesTextBlockGPUUsageDetectionSpeed {
            get {
                return ResourceManager.GetString("SwitchModesTextBlockGPUUsageDetectionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Battery powered devices.
        /// </summary>
        public static string SwitchModesTextBlockHeaderBatteryPowered {
            get {
                return ResourceManager.GetString("SwitchModesTextBlockHeaderBatteryPowered", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Conditions.
        /// </summary>
        public static string SwitchModesTextBlockHeaderConditions {
            get {
                return ResourceManager.GetString("SwitchModesTextBlockHeaderConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Dark Mode Hotkey.
        /// </summary>
        public static string SwitchModesTextBlockHeaderForceDarkHotkey {
            get {
                return ResourceManager.GetString("SwitchModesTextBlockHeaderForceDarkHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Light Mode Hotkey.
        /// </summary>
        public static string SwitchModesTextBlockHeaderForceLightHotkey {
            get {
                return ResourceManager.GetString("SwitchModesTextBlockHeaderForceLightHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string SwitchModesTextBlockHeaderHotkeys {
            get {
                return ResourceManager.GetString("SwitchModesTextBlockHeaderHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Forcing Theme Hotkey.
        /// </summary>
        public static string SwitchModesTextBlockHeaderNoForceHotkey {
            get {
                return ResourceManager.GetString("SwitchModesTextBlockHeaderNoForceHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum GPU usage to delay switching.
        /// </summary>
        public static string SwitchModesTextBlockMinimumUsage {
            get {
                return ResourceManager.GetString("SwitchModesTextBlockMinimumUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable system-wide hotkeys.
        /// </summary>
        public static string SwitchModesToggleHeaderHotkey {
            get {
                return ResourceManager.GetString("SwitchModesToggleHeaderHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended tools.
        /// </summary>
        public static string tbAppsTitleRecommendedTools {
            get {
                return ResourceManager.GetString("tbAppsTitleRecommendedTools", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This browser extension makes websites in Chrome, Firefox and Edge respect the system theme..
        /// </summary>
        public static string tbDarkReaderDescription {
            get {
                return ResourceManager.GetString("tbDarkReaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This feature is disabled while theme mode is enabled..
        /// </summary>
        public static string tbFeatureDisabledWhileThemeMode {
            get {
                return ResourceManager.GetString("tbFeatureDisabledWhileThemeMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This feature is disabled while wallpaper mode is enabled..
        /// </summary>
        public static string tbFeatureDisabledWhileWallpaperMode {
            get {
                return ResourceManager.GetString("tbFeatureDisabledWhileWallpaperMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Geo coordinates for your location.
        /// </summary>
        public static string tbGetCoordinates {
            get {
                return ResourceManager.GetString("tbGetCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Need help with a problem?.
        /// </summary>
        public static string tbHelp {
            get {
                return ResourceManager.GetString("tbHelp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Offers more features, but you need to set up a windows .theme file. Customize your desktop wallpaper per monitor, set a diashow, change your mouse cursor, set an accent color and individual sounds..
        /// </summary>
        public static string tbPickTheme {
            get {
                return ResourceManager.GetString("tbPickTheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Offers less features, but is easier to set up. Customize your desktop wallpaper for all monitors, individual monitors or set a background color..
        /// </summary>
        public static string tbPickWallpaper {
            get {
                return ResourceManager.GetString("tbPickWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Optional delay for activating grayscale color filter:.
        /// </summary>
        public static string tbSettingsColourFilterDelay {
            get {
                return ResourceManager.GetString("tbSettingsColourFilterDelay", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu We check for new versions of Auto Dark Mode in the background. When an update is available, we will notify you via toast notification.
        /// </summary>
        public static string tbUpdates {
            get {
                return ResourceManager.GetString("tbUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error occurred while applying the selected themes, we disabled theme switching.
        /// </summary>
        public static string ThemeApplyError1 {
            get {
                return ResourceManager.GetString("ThemeApplyError1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error occured while applying a .theme-file. Maybe your created theme got deleted or moved. This is why we deactivated theme switching for now. To re-enable it, please open Auto Dark Mode and configure {0} Settings..
        /// </summary>
        public static string ThemeApplyError2 {
            get {
                return ResourceManager.GetString("ThemeApplyError2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dark Theme:.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create your themes.
        /// </summary>
        public static string ThemeHeaderCreate {
            get {
                return ResourceManager.GetString("ThemeHeaderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pick your themes.
        /// </summary>
        public static string ThemeHeaderPick {
            get {
                return ResourceManager.GetString("ThemeHeaderPick", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light Theme:.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Restore themes when changed externally.
        /// </summary>
        public static string ThemePickerComboBoxKeepActive {
            get {
                return ResourceManager.GetString("ThemePickerComboBoxKeepActive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Flowers.
        /// </summary>
        public static string ThemePickerTheme10Flowers {
            get {
                return ResourceManager.GetString("ThemePickerTheme10Flowers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Windows.
        /// </summary>
        public static string ThemePickerTheme10Windows {
            get {
                return ResourceManager.GetString("ThemePickerTheme10Windows", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Windows 10.
        /// </summary>
        public static string ThemePickerTheme10Windows10 {
            get {
                return ResourceManager.GetString("ThemePickerTheme10Windows10", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Windows (Light).
        /// </summary>
        public static string ThemePickerTheme10WindowsLight {
            get {
                return ResourceManager.GetString("ThemePickerTheme10WindowsLight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Captured Motion.
        /// </summary>
        public static string ThemePickerTheme11CapturedMotion {
            get {
                return ResourceManager.GetString("ThemePickerTheme11CapturedMotion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Windows (Dark).
        /// </summary>
        public static string ThemePickerTheme11Dark {
            get {
                return ResourceManager.GetString("ThemePickerTheme11Dark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Flow.
        /// </summary>
        public static string ThemePickerTheme11Flow {
            get {
                return ResourceManager.GetString("ThemePickerTheme11Flow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Glow.
        /// </summary>
        public static string ThemePickerTheme11Glow {
            get {
                return ResourceManager.GetString("ThemePickerTheme11Glow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Windows (Light).
        /// </summary>
        public static string ThemePickerTheme11Light {
            get {
                return ResourceManager.GetString("ThemePickerTheme11Light", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sunrise.
        /// </summary>
        public static string ThemePickerTheme11Sunrise {
            get {
                return ResourceManager.GetString("ThemePickerTheme11Sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select mode:.
        /// </summary>
        public static string ThemeSelection {
            get {
                return ResourceManager.GetString("ThemeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Windows Theme (more features).
        /// </summary>
        public static string ThemeSelectionTheme {
            get {
                return ResourceManager.GetString("ThemeSelectionTheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Desktop Wallpaper (recommended).
        /// </summary>
        public static string ThemeSelectionWallaper {
            get {
                return ResourceManager.GetString("ThemeSelectionWallaper", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Theme.
        /// </summary>
        public static string ThemeTextBlockHeader {
            get {
                return ResourceManager.GetString("ThemeTextBlockHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enable Windows theme switch.
        /// </summary>
        public static string ThemeToggleSwichEnableTheme {
            get {
                return ResourceManager.GetString("ThemeToggleSwichEnableTheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Step.
        /// </summary>
        public static string ThemeTutorialStep {
            get {
                return ResourceManager.GetString("ThemeTutorialStep", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Click here to open Windows Theme settings..
        /// </summary>
        public static string ThemeTutorialStep1 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Now navigate to &apos;Colors&apos; and change the system color to &apos;Light&apos; for the light theme. Select your favorite Wallpaper, Mouse Cursor and Accent Color..
        /// </summary>
        public static string ThemeTutorialStep2 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Go back to theme settings and save your theme..
        /// </summary>
        public static string ThemeTutorialStep3 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Repeat this process for the dark theme..
        /// </summary>
        public static string ThemeTutorialStep4 {
            get {
                return ResourceManager.GetString("ThemeTutorialStep4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Latitude.
        /// </summary>
        public static string TimeNumberBoxHeaderLat {
            get {
                return ResourceManager.GetString("TimeNumberBoxHeaderLat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Longitude.
        /// </summary>
        public static string TimeNumberBoxHeaderLon {
            get {
                return ResourceManager.GetString("TimeNumberBoxHeaderLon", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Next update at.
        /// </summary>
        public static string TimePageNextUpdateAt {
            get {
                return ResourceManager.GetString("TimePageNextUpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Click Set to save changes..
        /// </summary>
        public static string TimeTextBlockClickOnSetMessage {
            get {
                return ResourceManager.GetString("TimeTextBlockClickOnSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Auto Dark Mode.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Off.
        /// </summary>
        public static string ToggleSwitchOff {
            get {
                return ResourceManager.GetString("ToggleSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu On.
        /// </summary>
        public static string ToggleSwitchOn {
            get {
                return ResourceManager.GetString("ToggleSwitchOn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu These options are disabled while using a Windows Theme.
        ///You can set them up individually in your Windows Theme..
        /// </summary>
        public static string ToolTipDisabledDueTheme {
            get {
                return ResourceManager.GetString("ToolTipDisabledDueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check for updates.
        /// </summary>
        public static string updateButton {
            get {
                return ResourceManager.GetString("updateButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu We check for updates at every program start..
        /// </summary>
        public static string updateInfoText {
            get {
                return ResourceManager.GetString("updateInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Automatically download and install new versions.
        /// </summary>
        public static string UpdatesCheckBoxAutoInstall {
            get {
                return ResourceManager.GetString("UpdatesCheckBoxAutoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Don&apos;t show notifications.
        /// </summary>
        public static string UpdatesCheckBoxSilent {
            get {
                return ResourceManager.GetString("UpdatesCheckBoxSilent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select update channel.
        /// </summary>
        public static string UpdatesCheckBoxUpdateChannel {
            get {
                return ResourceManager.GetString("UpdatesCheckBoxUpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check for updates when Auto Dark Mode starts.
        /// </summary>
        public static string UpdatesComboBoxAtStart {
            get {
                return ResourceManager.GetString("UpdatesComboBoxAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Every day.
        /// </summary>
        public static string UpdatesComboBoxInterval1 {
            get {
                return ResourceManager.GetString("UpdatesComboBoxInterval1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 14 days.
        /// </summary>
        public static string UpdatesComboBoxInterval14 {
            get {
                return ResourceManager.GetString("UpdatesComboBoxInterval14", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 3 days.
        /// </summary>
        public static string UpdatesComboBoxInterval3 {
            get {
                return ResourceManager.GetString("UpdatesComboBoxInterval3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 7 days.
        /// </summary>
        public static string UpdatesComboBoxInterval7 {
            get {
                return ResourceManager.GetString("UpdatesComboBoxInterval7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Last checked.
        /// </summary>
        public static string UpdatesTextBlockLastChecked {
            get {
                return ResourceManager.GetString("UpdatesTextBlockLastChecked", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu never.
        /// </summary>
        public static string UpdatesTextBlockLastCheckedNever {
            get {
                return ResourceManager.GetString("UpdatesTextBlockLastCheckedNever", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change how often we check for updates.
        /// </summary>
        public static string UpdatesTextBlockUpdateInterval {
            get {
                return ResourceManager.GetString("UpdatesTextBlockUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Welcome.
        /// </summary>
        public static string userFeedback {
            get {
                return ResourceManager.GetString("userFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Color.
        /// </summary>
        public static string WallpaperColor {
            get {
                return ResourceManager.GetString("WallpaperColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dark Theme.
        /// </summary>
        public static string WallpaperComboBoxItemDark {
            get {
                return ResourceManager.GetString("WallpaperComboBoxItemDark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light Theme.
        /// </summary>
        public static string WallpaperComboBoxItemLight {
            get {
                return ResourceManager.GetString("WallpaperComboBoxItemLight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Picture.
        /// </summary>
        public static string WallpaperComboBoxItemPicture {
            get {
                return ResourceManager.GetString("WallpaperComboBoxItemPicture", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Picture (multiple monitors).
        /// </summary>
        public static string WallpaperComboBoxItemPictureMM {
            get {
                return ResourceManager.GetString("WallpaperComboBoxItemPictureMM", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Solid color.
        /// </summary>
        public static string WallpaperComboBoxItemSolidColor {
            get {
                return ResourceManager.GetString("WallpaperComboBoxItemSolidColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mode.
        /// </summary>
        public static string WallpaperComboBoxMode {
            get {
                return ResourceManager.GetString("WallpaperComboBoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Monitor.
        /// </summary>
        public static string WallpaperComboBoxMonitor {
            get {
                return ResourceManager.GetString("WallpaperComboBoxMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Type.
        /// </summary>
        public static string WallpaperComboBoxType {
            get {
                return ResourceManager.GetString("WallpaperComboBoxType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Remove disconnected monitors.
        /// </summary>
        public static string WallpaperHyperLinkRemoveDisconnected {
            get {
                return ResourceManager.GetString("WallpaperHyperLinkRemoveDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wallpaper.
        /// </summary>
        public static string WallpaperTextBlockHeader {
            get {
                return ResourceManager.GetString("WallpaperTextBlockHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Color.
        /// </summary>
        public static string WallpaperTextBlockHeaderColor {
            get {
                return ResourceManager.GetString("WallpaperTextBlockHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hex code.
        /// </summary>
        public static string WallpaperTextBoxHeaderHex {
            get {
                return ResourceManager.GetString("WallpaperTextBoxHeaderHex", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enable wallpaper switch.
        /// </summary>
        public static string WallpaperToggleSwitch {
            get {
                return ResourceManager.GetString("WallpaperToggleSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Activate the checkbox to enable automatic theme switching.
        /// </summary>
        public static string welcomeText {
            get {
                return ResourceManager.GetString("welcomeText", resourceCulture);
            }
        }
    }
}
