namespace AutoDarkModeApp.Views;

internal static class UiText
{
    private static readonly IReadOnlyDictionary<string, (string Zh, string En)> Text = new Dictionary<string, (string, string)>(StringComparer.Ordinal)
    {
        ["SensorNav"] = ("环境光传感器", "Light sensor"), ["BrightnessNav"] = ("自适应亮度", "Adaptive brightness"),
        ["ThemeNav"] = ("自适应主题", "Adaptive theme"), ["PersonalizationNav"] = ("个性化", "Personalization"),
        ["SettingsNav"] = ("设置", "Settings"), ["AboutNav"] = ("关于", "About"),
        ["SensorPageTitle"] = ("环境光传感器", "Light sensor"), ["SensorSubtitle"] = ("查看环境光与设备连接状态", "View ambient-light readings and device status"),
        ["BrightnessPageTitle"] = ("自适应亮度", "Adaptive brightness"), ["BrightnessSubtitle"] = ("调整 lux 到外接显示器亮度的映射", "Map ambient lux to external-display brightness"),
        ["ThemePageTitle"] = ("自适应主题", "Adaptive theme"), ["ThemeSubtitle"] = ("使用环境光阈值带滞回切换系统外观", "Switch Windows appearance with ambient-light thresholds and hysteresis"),
        ["PersonalizationPageTitle"] = ("个性化", "Personalization"), ["PersonalizationSubtitle"] = ("为浅色与深色主题分别设置系统外观", "Configure system appearance separately for light and dark themes"),
        ["SettingsPageTitle"] = ("设置", "Settings"), ["SettingsSubtitle"] = ("管理登录启动与界面语言", "Manage sign-in startup and interface language"),
        ["AboutPageTitle"] = ("关于", "About"), ["AboutSubtitle"] = ("应用信息与参考项目", "Application information and design reference"),
        ["BackgroundTitle"] = ("个性化 › 背景", "Personalization › Background"), ["BackgroundSubtitle"] = ("按浅色与深色主题分别保存壁纸", "Set separate wallpaper and positioning for light and dark themes"),
        ["AccentTitle"] = ("个性化 › 主题色", "Personalization › Accent color"), ["AccentSubtitle"] = ("应用到 Windows 的真实系统强调色", "Apply the real Windows system accent color"),
        ["CursorTitle"] = ("个性化 › 光标", "Personalization › Cursors"), ["CursorSubtitle"] = ("选择本机存在的 Windows 光标方案", "Choose cursor schemes available on this PC"),
        ["Back"] = ("返回个性化", "Back to Personalization"),
        ["SensorCardTitle"] = ("环境光传感器", "Ambient-light sensors"), ["SensorCardDescription"] = ("Pico USB CDC 与 Windows HID 光感分别检测，任一路径都可独立使用。", "Pico USB CDC and Windows HID are detected independently."),
        ["CdcLabel"] = ("Pico USB CDC", "Pico USB CDC"), ["HidLabel"] = ("Windows HID 光感", "Windows HID sensor"), ["LiveLuxLabel"] = ("实时环境光", "Current ambient light"),
        ["LiveLuxWaiting"] = ("等待光感读数", "Waiting for sensor reading"), ["FirmwareTitle"] = ("Pico 固件", "Pico firmware"), ["FirmwareHardware"] = ("RP2040 + BH1750", "RP2040 + BH1750"),
        ["FirmwareInstructions"] = ("按住 BOOTSEL 并连接 Pico USB，再检测 RPI-RP2 启动盘。仅在确认后复制固件。", "Hold BOOTSEL while connecting the Pico, then detect its RPI-RP2 boot drive. Firmware is copied only after confirmation."),
        ["FirmwareButton"] = ("检测并准备固件", "Detect and prepare firmware"), ["StartupExpander"] = ("登录启动", "Start at sign-in"),
        ["StartupSummary"] = ("在设置页面启用后，应用会在当前用户登录时启动。", "When enabled in Settings, the app starts when this Windows user signs in."),
        ["OpenSettings"] = ("打开设置", "Open Settings"),
        ["SafePreviewText"] = ("安全预览已启用：不会打开 CDC、控制显示器或修改主题、壁纸、强调色、光标、启动项与固件盘。", "Safe preview is on: no CDC access, monitor control, system appearance, startup, or firmware-drive writes."),
        ["DryRunSystemSafeText"] = ("DDC/CI 亮度正在预览；主题、壁纸、强调色、光标、启动项与固件盘写入均已禁用。", "Brightness is in dry-run preview; theme, wallpaper, accent, cursor, startup, and firmware-drive writes are disabled."),
        ["SafePreviewStatus"] = ("安全预览：已阻止系统写入与固件复制。", "Safe preview: system writes and firmware copying are disabled."),
        ["SafeCdcStatus"] = ("安全预览：CDC 串口与 DDC/CI 均已停用", "Safe preview: CDC and DDC/CI are disabled"),
        ["BrightnessDisabledStatus"] = ("自动亮度调节已关闭；传感器仍保持运行。", "Automatic brightness is off; sensors remain active."),
        ["BrightnessSwitch"] = ("启用自动亮度调节", "Enable automatic brightness adjustment"),
        ["BrightnessHelp"] = ("关闭后停止 DDC/CI 写入，但环境光传感器继续检测。曲线纵轴使用亮度百分比；VCP 0x10 不是 nit。", "When off, DDC/CI writes stop while sensors keep running. The curve uses brightness percent: VCP 0x10 is not a nit value."),
        ["PresetHeader"] = ("命名曲线预设", "Named curve preset"), ["SavePreset"] = ("另存预设", "Save preset as…"), ["DeletePreset"] = ("删除预设", "Delete preset"),
        ["CurveTitle"] = ("lux → DDC/CI 亮度", "lux → DDC/CI brightness"), ["CurveDescription"] = ("拖动控制点预览。横轴 log10(1 + lux)，纵轴 0–100%。", "Drag control points to preview. X uses log10(1 + lux); Y is 0–100%."),
        ["CurveYAxisLabel"] = ("亮度", "Brightness"), ["CurveXAxisLabel"] = ("环境光 · lux（log10(1 + lux)）", "Ambient light · lux (log10(1 + lux))"),
        ["SelectedPointLux"] = ("选中点 · 环境光（lux）", "Selected point · ambient light (lux)"), ["SelectedPointBrightness"] = ("显示器亮度（0–100%）", "Display brightness (0–100%)"),
        ["RemovePoint"] = ("删除选中点", "Remove selected point"), ["NewLux"] = ("添加 lux", "New lux"), ["NewBrightness"] = ("添加亮度 %", "New brightness %"), ["AddPoint"] = ("添加控制点", "Add point"),
        ["CurvePreview"] = ("曲线预览：仅更新本地预览", "Curve preview updates locally only"), ["CurveSafety"] = ("拖动预览不写显示器；到设置页点击“应用并保存”才会启用。", "Dragging only previews. Use Apply and save on the Settings page to activate the curve."),
        ["ThemeSwitch"] = ("启用自动主题切换", "Enable automatic theme switching"),
        ["ThemeHelp"] = ("光线低于深色阈值切换为深色，高于浅色阈值切换为浅色；阈值之间保留当前主题，避免频繁切换。", "Lux at or below the dark threshold selects dark mode; lux at or above the light threshold selects light mode. The band between them prevents rapid switching."),
        ["DarkThreshold"] = ("深色阈值 ≤", "Dark at or below (lux)"), ["LightThreshold"] = ("浅色阈值 ≥", "Light at or above (lux)"), ["CurrentLight"] = ("当前环境光", "Current ambient light"),
        ["ThemePersonalizationExpander"] = ("主题外观个性化", "Theme appearance options"), ["ThemePersonalizationHelp"] = ("背景、强调色和光标使用各自独立开关；自动主题关闭时不会自动应用这些系统项。", "Wallpaper, accent color, and cursor each have their own switch. They are not changed automatically while theme automation is off."), ["OpenPersonalization"] = ("打开个性化", "Open Personalization"),
        ["PersonalizationIntro"] = ("为深色与浅色外观分别设置背景、强调色和光标方案。", "Set separate wallpaper, accent color, and cursor schemes for dark and light themes."),
        ["BackgroundCard"] = ("背景", "Background"), ["BackgroundCardDescription"] = ("为浅色与深色外观选择壁纸和位置模式。", "Choose wallpapers and positioning for light and dark themes."),
        ["AccentCard"] = ("主题色", "Accent color"), ["AccentCardDescription"] = ("跟随壁纸自动取色，或分别选择浅色与深色强调色。", "Pick a color from each wallpaper or select separate accent colors."),
        ["CursorCard"] = ("光标", "Cursors"), ["CursorCardDescription"] = ("使用系统中已有的浅色与深色光标方案。", "Choose light and dark cursor schemes installed in Windows."),
        ["WallpaperSwitch"] = ("启用壁纸切换", "Enable wallpaper switching"), ["WallpaperHelp"] = ("只有自动主题切换开启时，系统才会自动应用对应壁纸。", "Wallpapers are applied only when automatic theme switching is enabled."),
        ["EditTheme"] = ("编辑主题", "Edit theme"), ["Light"] = ("浅色", "Light"), ["Dark"] = ("深色", "Dark"), ["ChooseImage"] = ("选择图片", "Choose image"),
        ["Position"] = ("位置模式", "Position"), ["Fill"] = ("填充", "Fill"), ["Fit"] = ("适应", "Fit"), ["Stretch"] = ("拉伸", "Stretch"), ["Tile"] = ("平铺", "Tile"), ["Center"] = ("居中", "Center"),
        ["ChooseWallpaperPreview"] = ("选择一张图片预览", "Choose an image to preview"), ["WallpaperMissingPreview"] = ("图片路径不存在或无法预览", "Image is missing or cannot be previewed"),
        ["AccentSwitch"] = ("启用系统强调色切换", "Enable system accent switching"), ["AccentHelp"] = ("自动模式从对应壁纸提取强调色；手动模式使用为浅色与深色分别保存的颜色。", "Automatic mode samples the matching wallpaper; manual mode uses separate saved colors."),
        ["Mode"] = ("取色模式", "Color mode"), ["Automatic"] = ("自动（随壁纸）", "Automatic (from wallpaper)"), ["Manual"] = ("手动", "Manual"), ["SelectedColor"] = ("当前选择", "Selected color"), ["Palette"] = ("Windows 色板", "Windows palette"),
        ["AccentApplyNotice"] = ("系统强调色只会在自动主题切换实际发生时应用。", "The system accent is applied on the next automatic theme switch."),
        ["CursorSwitch"] = ("启用光标方案切换", "Enable cursor scheme switching"), ["CursorHelp"] = ("只列出本机 Windows 当前可用的真实光标方案；缺少文件的方案不会应用。", "Only cursor schemes with files present on this PC are listed."),
        ["LightCursorScheme"] = ("浅色主题光标", "Light-theme cursor"), ["DarkCursorScheme"] = ("深色主题光标", "Dark-theme cursor"), ["OpenCursorSettings"] = ("打开 Windows 鼠标指针设置", "Open Windows mouse pointer settings"),
        ["StartupTitle"] = ("登录启动", "Start at sign-in"), ["StartupSwitch"] = ("登录 Windows 时启动并最小化", "Start minimized when Windows starts"),
        ["StartupHelp"] = ("设置仅作用于当前 Windows 用户，不需要管理员权限。保存后立即更新登录启动项。", "Applies to this Windows user only. Saving updates the sign-in entry; no administrator rights are needed."),
        ["LanguageTitle"] = ("界面语言", "Interface language"), ["Language"] = ("语言", "Language"), ["SystemLanguage"] = ("跟随系统", "Follow system"), ["SimplifiedChinese"] = ("简体中文", "Simplified Chinese"), ["English"] = ("English", "English"),
        ["LanguageNotice"] = ("语言立即切换；在设置页点击“应用并保存”后，下次启动时继续使用。", "Language changes immediately and is saved for the next launch when you choose Apply and save on the Settings page."),
        ["AboutName"] = ("Adaptive Brightness", "Adaptive Brightness"), ["AboutDescription"] = ("使用环境光传感器，控制外接显示器亮度与 Windows 外观。", "Uses ambient-light sensors to adjust external-display brightness and Windows appearance."),
        ["AboutLicense"] = ("界面独立实现。Auto Dark Mode 作为设计参考，其代码与资源未复制；本项目许可证以仓库为准。", "The interface is independently implemented. Auto Dark Mode was a design reference; no code or assets were copied. See this repository for the project license."),
        ["ReferenceProject"] = ("Auto Dark Mode 参考项目", "Auto Dark Mode reference project"), ["VersionLabel"] = ("版本", "Version"),
        ["ApplySave"] = ("应用并保存", "Apply and save"), ["SavedStatus"] = ("设置已应用并保存。", "Settings applied and saved."), ["SaveFailed"] = ("保存失败：{0}", "Save failed: {0}"), ["SaveFailedTitle"] = ("无法保存设置", "Could not save settings"), ["CloseButton"] = ("关闭", "Close"), ["CancelButton"] = ("取消", "Cancel"),
        ["ToggleOn"] = ("开启", "On"), ["ToggleOff"] = ("关闭", "Off"),
        ["LanguagePendingStatus"] = ("界面语言已切换，尚未保存。", "Interface language changed; save to keep it."), ["WallpaperPendingStatus"] = ("壁纸选择尚未保存；不会立即更改桌面。", "Wallpaper selection is not saved and has not changed the desktop."),
        ["CustomizationPendingStatus"] = ("个性化草稿已更新，尚未保存或应用到系统。", "Personalization draft changed; it has not been saved or applied to Windows."),
        ["AccentApplyManualNotice"] = ("手动强调色只会在下次自动主题切换时应用到 Windows。", "The selected manual accent is applied to Windows on the next automatic theme switch."),
        ["CurvePendingStatus"] = ("曲线预览已更新；尚未写入设备。", "Curve preview updated; the monitor has not been changed."),
        ["CurveGapError"] = ("此 lux 会与相邻控制点重叠，请留出可拖动间距。", "This lux overlaps a neighboring point. Leave enough space to drag the handles."),
        ["CurveOrderError"] = ("所选点的 lux 必须位于相邻控制点之间。", "The selected lux must stay between its neighboring control points."),
        ["CurveMinimumPoints"] = ("亮度曲线至少保留两个控制点。", "A brightness curve must keep at least two points."),
        ["InvalidLux"] = ("lux 必须是非负有限数值。", "Lux must be a finite non-negative number."),
        ["InvalidBrightness"] = ("亮度必须在 0 到 100 之间。", "Brightness must be between 0 and 100."),
        ["InvalidNewPoint"] = ("请输入非负有限 lux，以及 0–100% 的亮度。", "Enter a finite non-negative lux value and brightness from 0–100%."),
        ["PresetPreviewStatus"] = ("已加载预设为本地预览；应用前不会改变显示器。", "Preset loaded for local preview; the monitor is unchanged until you apply it."),
        ["PresetNamePrompt"] = ("为当前曲线输入一个预设名称。", "Enter a name for the current curve."),
        ["PresetNamePlaceholder"] = ("例如：夜间办公", "For example: Night work"),
        ["PresetSaveTitle"] = ("保存亮度曲线预设", "Save brightness curve preset"),
        ["PresetNameInvalid"] = ("预设名称不能为空，且不能超过 64 个字符。", "Preset name is required and must be 64 characters or fewer."),
        ["PresetSavedStatus"] = ("预设已保存到本地设置；尚未应用到显示器。", "Preset saved to local settings; it has not been applied to the monitor."),
        ["PresetDeletedStatus"] = ("预设已从本地设置中删除。", "Preset deleted from local settings."),
        ["ActivePresetSaveWithApply"] = ("当前预设正在使用。要保存修改，请到设置页点击“应用并保存”。", "This is the active preset. Use Apply and save on the Settings page to activate edits to it."),
        ["ActivePresetDeleteError"] = ("当前正在使用的预设不能删除。请先应用另一个预设。", "The active preset cannot be deleted. Apply another preset first."),
        ["LastPresetDeleteError"] = ("至少保留一个命名曲线预设。", "Keep at least one named curve preset."),
        ["ThresholdPendingStatus"] = ("阈值滑轨已更新；尚未写入系统。", "Threshold track updated; Windows has not been changed."),
        ["ThresholdOrderError"] = ("深色阈值必须小于浅色阈值。", "The dark threshold must be lower than the light threshold."),
        ["ThresholdGapError"] = ("两个阈值太接近，滑轨控制点无法分开。", "The thresholds are too close for distinct slider handles."),
        ["NoCursorSchemes"] = ("未找到可用的 Windows 光标方案。", "No usable Windows cursor schemes were found."),
        ["FirmwareMissingStatus"] = ("发布包中缺少 RP2040 UF2 固件。", "The RP2040 UF2 firmware is missing from this package."), ["SafeFirmwareStatus"] = ("安全预览期间禁止复制固件。", "Firmware copying is disabled in safe preview."),
        ["BootDriveNotFound"] = ("未检测到 RPI-RP2 启动盘。请按住 BOOTSEL 连接 Pico 后重试。", "RPI-RP2 boot drive not found. Hold BOOTSEL while connecting the Pico, then retry."),
        ["BootDriveAmbiguous"] = ("检测到多个 RP2040 启动盘；请只连接一个后重试。", "Multiple RP2040 boot drives were found. Leave one connected and retry."),
        ["FirmwareConfirmTitle"] = ("确认复制并烧录 RP2040 固件", "Confirm RP2040 firmware copy"), ["FirmwareConfirmBody"] = ("即将把经校验的固件复制到 {0}（{1:N0} 字节）。Pico 将重启并替换当前程序。只有在 BOOTSEL 模式且目标盘标识正确时继续。", "The validated firmware ({1:N0} bytes) will be copied to {0}. The Pico will reboot and replace its current program. Continue only if the drive is the BOOTSEL volume."), ["FirmwareConfirmButton"] = ("复制并烧录", "Copy firmware"),
        ["FirmwareCopiedStatus"] = ("固件文件已复制。请等待 Pico 重启，再查看 CDC/HID 连接状态。", "Firmware file copied. Wait for the Pico to reboot, then check CDC/HID status."), ["FirmwareSubmittedStatus"] = ("UF2 已提交给启动盘；启动盘消失通常表示设备正在重启。", "UF2 was submitted. The boot drive normally disappears while the Pico reboots."), ["FirmwareCopyFailed"] = ("复制固件失败：{0}", "Firmware copy failed: {0}"),
    };

    public static string Get(string key, string language) => Text.TryGetValue(key, out var value)
        ? (language.StartsWith("en", StringComparison.OrdinalIgnoreCase) ? value.En : value.Zh)
        : key;

    public static string TranslateStatus(string status)
    {
        if (string.IsNullOrEmpty(status)) return status;
        var map = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Waiting for Pico USB CDC sensor"] = "等待 Pico USB CDC 传感器",
            ["正在检测 Windows HID 环境光传感器"] = "Detecting Windows HID ambient-light sensor",
            ["已检测到 Windows HID 传感器，等待读数"] = "Windows HID sensor found; waiting for a reading",
            ["HID 光感无新读数，正在重新检测"] = "No recent HID readings; reconnecting",
            ["旧版托盘控制器仍在运行"] = "Legacy tray controller is running",
            ["无法取得 CDC 控制权"] = "Could not acquire CDC control",
            ["等待 Pico USB CDC 传感器"] = "Waiting for Pico USB CDC sensor",
            ["CDC 已连接"] = "CDC connected",
            ["CDC 读取失败，正在重连"] = "CDC read failed; reconnecting",
            ["仅计算阈值；未修改 Windows 设置"] = "thresholds calculated only; Windows settings are unchanged",
            ["自动主题切换关闭"] = "automatic theme switching is off",
            ["系统外观未写入"] = "Windows appearance is unchanged",
            ["系统外观未修改"] = "Windows appearance is unchanged",
            ["保留当前壁纸"] = "Keeping the current wallpaper",
            ["已应用对应壁纸"] = "Applied the wallpaper for this theme",
            ["强调色未更改（无法从壁纸取色）"] = "Accent color unchanged (could not sample the wallpaper)",
            ["已应用 Windows 强调色"] = "Applied Windows accent color",
            ["个性化设置未启用"] = "Personalization options are disabled",
            ["强调色应用失败"] = "Accent color apply failed",
            ["外观自动切换已关闭"] = "Automatic theme switching is off",
            ["等待 HID 光感读数"] = "Waiting for HID ambient-light reading",
            ["安全预览：外观阈值只计算，不修改 Windows 设置"] = "Safe preview: theme thresholds are calculated without changing Windows settings",
            ["未检测到 Windows HID 环境光传感器"] = "Windows HID ambient-light sensor not detected",
            ["已停止"] = "Stopped",
            ["正在等待"] = "Waiting",
            ["正在检测"] = "Detecting",
            ["已连接 Windows HID 环境光传感器"] = "Connected to Windows HID ambient-light sensor",
            ["环境光"] = "ambient light",
            ["传感器"] = "sensor",
            ["已连接"] = "Connected",
            ["等待"] = "Waiting",
            ["亮度控制已暂停"] = "brightness control paused",
            ["为避免争用 Pico CDC"] = "to avoid Pico CDC contention",
            ["另一个 Adaptive Brightness 控制器正在运行"] = "Another Adaptive Brightness controller is running",
            ["安全预览"] = "Safe preview",
            ["预览"] = "preview",
            ["运行中"] = "active",
            ["亮度"] = "brightness",
            ["未连接"] = "disconnected",
            ["不可用"] = "unavailable",
            ["主题切换失败"] = "Theme switch failed",
            ["已切换为浅色主题"] = "Switched to light theme",
            ["已切换为深色主题"] = "Switched to dark theme",
            ["当前为浅色主题"] = "Current theme is light",
            ["当前为深色主题"] = "Current theme is dark",
            ["浅色主题"] = "light theme",
            ["深色主题"] = "dark theme",
            ["浅色"] = "light",
            ["深色"] = "dark",
            ["滞回带"] = "hysteresis band",
            ["目标"] = "target",
            ["预览"] = "preview",
            ["系统主题"] = "Windows theme",
            ["壁纸"] = "wallpaper",
            ["强调色"] = "accent color",
            ["光标方案"] = "cursor scheme",
            ["保持浅色主题"] = "keeping light theme",
            ["保持深色主题"] = "keeping dark theme",
            ["lux"] = "lux",
            ["正在重连"] = "reconnecting",
            ["DDC/CI"] = "DDC/CI",
            ["CDC"] = "CDC",
            ["Pico"] = "Pico",
            ["深色阈值必须是非负有限数值。"] = "Dark threshold must be a finite non-negative number.",
            ["浅色阈值必须是有限数值，并且高于深色阈值。"] = "Light threshold must be finite and greater than the dark threshold.",
            ["曲线至少需要两个点。"] = "A curve needs at least two points.",
            ["亮度曲线至少需要两个点。"] = "A brightness curve needs at least two points.",
            ["曲线 lux 必须是非负有限数值。"] = "Curve lux values must be finite and non-negative.",
            ["曲线亮度必须在 0 到 100 之间。"] = "Curve brightness must be between 0 and 100.",
            ["曲线 lux 必须互不相同。"] = "Curve lux values must be unique.",
            ["预设名称不能为空，且不能超过 64 个字符。"] = "Preset names are required and must be 64 characters or fewer.",
            ["预设名称不能重复。"] = "Preset names must be unique.",
            ["当前曲线预设不存在。"] = "The active curve preset does not exist.",
            ["界面语言仅支持跟随系统、简体中文或 English。"] = "Interface language must be System, Simplified Chinese, or English.",
            ["壁纸位置模式无效。"] = "Wallpaper position setting is invalid.",
            ["强调色设置无效。"] = "Accent color setting is invalid.",
            ["主题阈值" ] = "Theme thresholds",
            ["UF2 文件长度无效或超出安全校验范围。"] = "UF2 length is invalid or exceeds the validation limit.",
            ["UF2 文件包含不完整的数据块。"] = "UF2 contains an incomplete block.",
            ["UF2 第 "] = "UF2 block ",
            [" 的标识签名无效。"] = " has an invalid signature.",
            ["UF2 固件不是带 RP2040 family ID 的映像。"] = "This UF2 does not include the RP2040 family ID.",
            ["UF2 块编号或声明的总块数不一致。"] = "UF2 block numbers or declared block count do not match.",
            ["RP2040 UF2 数据块的有效载荷长度不是 256 字节。"] = "RP2040 UF2 payload blocks must be 256 bytes.",
            ["壁纸文件不存在："] = "Wallpaper file not found: ",
            ["壁纸应用失败"] = "Wallpaper apply failed",
            ["强调色格式无效"] = "Accent color format is invalid",
            ["光标方案不可用："] = "Cursor scheme unavailable: ",
            ["光标文件缺失，未应用方案："] = "Cursor files are missing; scheme not applied: ",
            ["光标方案刷新失败"] = "Cursor scheme refresh failed",
            ["光标方案应用失败"] = "Cursor scheme apply failed",
            ["未检测到 RPI-RP2 启动盘。请按住 BOOTSEL 连接 Pico 后重试。"] = "RPI-RP2 boot drive not found. Hold BOOTSEL while connecting the Pico, then retry.",
            ["检测到多个 RP2040 启动盘；请只连接一个后重试。"] = "Multiple RP2040 boot drives were found. Leave one connected and retry."
        };
        status = System.Text.RegularExpressions.Regex.Replace(status,
            @"(?<count>\d+)\s*台显示器已到目标亮度",
            match => int.TryParse(match.Groups["count"].Value, out var count)
                ? $"{count} {(count == 1 ? "display reached" : "displays reached")} target brightness"
                : match.Value,
            System.Text.RegularExpressions.RegexOptions.CultureInvariant);
        status = System.Text.RegularExpressions.Regex.Replace(status,
            @"DDC/CI 失败（读取 (?<read>\d+)，写入 (?<write>\d+)）",
            match => $"DDC/CI failed (read {match.Groups["read"].Value}, write {match.Groups["write"].Value})",
            System.Text.RegularExpressions.RegexOptions.CultureInvariant);
        if (status.StartsWith("外观自动切换已关闭", StringComparison.Ordinal)) return "Automatic theme switching is off";
        if (status.StartsWith("等待 HID", StringComparison.Ordinal)) return "Waiting for HID ambient-light reading";
        if (status.StartsWith("HID 光感不可用：", StringComparison.Ordinal)) return "HID sensor unavailable: " + status["HID 光感不可用：".Length..];
        if (status.StartsWith("已连接 Windows HID", StringComparison.Ordinal)) return status.Replace("已连接 Windows HID 环境光传感器", "Connected to Windows HID ambient-light sensor", StringComparison.Ordinal);
        foreach (var pair in map) status = status.Replace(pair.Key, pair.Value, StringComparison.Ordinal);
        status = status.Replace("，", ", ", StringComparison.Ordinal)
            .Replace("：", ": ", StringComparison.Ordinal)
            .Replace("；", "; ", StringComparison.Ordinal)
            .Replace("（", " (", StringComparison.Ordinal)
            .Replace("）", ")", StringComparison.Ordinal);
        status = System.Text.RegularExpressions.Regex.Replace(status, @"\s{2,}", " ");
        return status;
    }
}
