# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '42 16 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'No updates have been provided to this issue after 60 days of inactivity. The issue will be automatically closed in 7 days.'
        stale-issue-label: 'no activity'
        stale-pr-label: 'no activity'
        days-before-pr-stale: -1
        exempt-issue-labels: >
            enhancement, pr-welcome, known issue, UX, good first issue, bug, wontfix, in progress,
            area-app settings, area-cross integration, area-installation, area-internal,
            area-localization, area-repository, area-script, area-store, area-UX,
            area-windows bug, area-windows settings, area-windows themes, area-winui3
